![sql](img/sql-logo.jpg)

# A beginner's guide to databases, SQL, & using them with `pandas`

**Scenario:** You are a data analyst for the Homeland Security, trying to create reports on the active airports world wide. The data you need to access is in a SQL database. YOu need to be able to query for the data in a database!

## Learning goals:
- Goal 1: Summarize the use case for sql in the data science skill set
- Goal 2: Define key sql terminology
- Goal 3: Get information about DB schema and table structure
- Goal 4: Use basic SQL commands:
    - Construct SQL queries
    - Use JOIN to merge tables along logical columns
    - Grouping Data with SQL
- Goal 5: Query data from pandas dataframes using SQL
- Goal 6: Convert SQL to pandas

## Goal 1: Summarize

[Netflix has a great article](https://medium.com/netflix-techblog/notebook-innovation-591ee3221233) describing three different data roles at their company, their different needs, and their toolsets.

![netflix](img/netflix-data-roles.jpeg)

Examining that graphic, SQL shows up as one of the tools of the _Data Engineer_

Data Engineers provide the essential data architecture services that make data science possible.

![hierarchy](img/ai-hierachy.png)

[Source: Monica Rogati’s fantastic Medium post “The AI Hierarchy of Needs”
](https://hackernoon.com/the-ai-hierarchy-of-needs-18f111fcc007)

![etl](img/etl.png)

[img source: Jeff Hammerbacher’s slide from UC Berkeley CS 194 course ](https://bcourses.berkeley.edu/courses/1377158/pages/cs-194-16-introduction-to-data-science-fall-2015)

### What is a Relational Database? 

![rdb](img/relational-dbms-model.png)
[reference for image ](https://www.studytonight.com/dbms/database-model.php)

### POPULAR RDBMS

- SQLite
- MySQL
- PostgreSql
- Oracle DB
- SQL Server

***
## Goal 2: Database terminology

### Relational Database Schema

![schema](img/MySQL_Schema_Music_Example.png)

[source of image](https://database.guide/what-is-a-database-schema/)

### Table columns view
![table example](img/columns.png)

### Terminology

- Schema
- Primary Key
- Foreign Key
- Structured queries
- Views

***
### SQLite

![sqlite](img/SQLite-Python.jpg)

"SQLite is a C library that provides a lightweight disk-based database that doesn’t require a separate server process and allows accessing the database using a nonstandard variant of the SQL query language. Some applications can use SQLite for internal data storage. It’s also possible to prototype an application using SQLite and then port the code to a larger database such as PostgreSQL or Oracle." - [sqlite documentation](https://docs.python.org/2/library/sqlite3.html)

## But what about connecting to database servers?

To connect to an Oracle database server there is a different package, `cx_Oracle`. The documentation for that package is [here](https://oracle.github.io/python-cx_Oracle/)

***
## Goal 3: Get going with sqlite!

In [1]:
import sqlite3

In [ ]:
sqlite3.

#### Load a DB object with `connect` and `cursor`

In [2]:
con = sqlite3.connect('flights.db')
cursor = con.cursor()

#### Use sqlite_master to find all the tables in the schema
Get the schema of a database from a db in sqlite

In [47]:
sqlite3.connect('flights.db').cursor().execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()

[('airports',), ('airlines',), ('routes',)]

In [11]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('airports',), ('airlines',), ('routes',)]

In [12]:
cursor.execute("SELECT name, type FROM sqlite_master;")
print(cursor.fetchall())

[('airports', 'table'), ('ix_airports_index', 'index'), ('airlines', 'table'), ('ix_airlines_index', 'index'), ('routes', 'table'), ('ix_routes_index', 'index')]

In [9]:
cursor.execute("SELECT * FROM sqlite_master;")
res = cursor.fetchall()
for r in res:
    print(r)

('table', 'airports', 'airports', 2, 'CREATE TABLE airports (\n[index] INTEGER,\n  [id] TEXT,\n  [name] TEXT,\n  [city] TEXT,\n  [country] TEXT,\n  [code] TEXT,\n  [icao] TEXT,\n  [latitude] TEXT,\n  [longitude] TEXT,\n  [altitude] TEXT,\n  [offset] TEXT,\n  [dst] TEXT,\n  [timezone] TEXT\n)')
('index', 'ix_airports_index', 'airports', 3, 'CREATE INDEX ix_airports_index ON airports ([index])')
('table', 'airlines', 'airlines', 945, 'CREATE TABLE airlines (\n[index] INTEGER,\n  [id] TEXT,\n  [name] TEXT,\n  [alias] TEXT,\n  [iata] TEXT,\n  [icao] TEXT,\n  [callsign] TEXT,\n  [country] TEXT,\n  [active] TEXT\n)')
('index', 'ix_airlines_index', 'airlines', 946, 'CREATE INDEX ix_airlines_index ON airlines ([index])')
('table', 'routes', 'routes', 1393, 'CREATE TABLE routes (\n[index] INTEGER,\n  [airline] TEXT,\n  [airline_id] TEXT,\n  [source] TEXT,\n  [source_id] TEXT,\n  [dest] TEXT,\n  [dest_id] TEXT,\n  [codeshare] TEXT,\n  [stops] TEXT,\n  [equipment] TEXT\n)')
('index', 'ix_routes_index', 'routes', 1394, 'CREATE INDEX ix_routes_index ON routes ([index])')

#### Get information about one table

**A note about** `execute`<br>
Each time you use it, you reset the value of cursor

In [17]:
cursor.execute("SELECT * FROM airports").fetchone()

(0,
 '1',
 'Goroka',
 'Goroka',
 'Papua New Guinea',
 'GKA',
 'AYGA',
 '-6.081689',
 '145.391881',
 '5282',
 '10',
 'U',
 'Pacific/Port_Moresby')

In [20]:
cursor.execute("SELECT * FROM airports")

In [23]:
cursor.fetchmany(4)

[(8,
  '9',
  'Sondre Stromfjord',
  'Sondrestrom',
  'Greenland',
  'SFJ',
  'BGSF',
  '67.016969',
  '-50.689325',
  '165',
  '-3',
  'E',
  'America/Godthab'),
 (9,
  '10',
  'Thule Air Base',
  'Thule',
  'Greenland',
  'THU',
  'BGTL',
  '76.531203',
  '-68.703161',
  '251',
  '-4',
  'E',
  'America/Thule'),
 (10,
  '11',
  'Akureyri',
  'Akureyri',
  'Iceland',
  'AEY',
  'BIAR',
  '65.659994',
  '-18.072703',
  '6',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (11,
  '12',
  'Egilsstadir',
  'Egilsstadir',
  'Iceland',
  'EGS',
  'BIEG',
  '65.283333',
  '-14.401389',
  '76',
  '0',
  'N',
  'Atlantic/Reykjavik')]

#### Use description

In [24]:
cursor.description

(('index', None, None, None, None, None, None),
 ('id', None, None, None, None, None, None),
 ('name', None, None, None, None, None, None),
 ('city', None, None, None, None, None, None),
 ('country', None, None, None, None, None, None),
 ('code', None, None, None, None, None, None),
 ('icao', None, None, None, None, None, None),
 ('latitude', None, None, None, None, None, None),
 ('longitude', None, None, None, None, None, None),
 ('altitude', None, None, None, None, None, None),
 ('offset', None, None, None, None, None, None),
 ('dst', None, None, None, None, None, None),
 ('timezone', None, None, None, None, None, None))

#### Or use `Pragma`
`Pragma` tool [link here](https://www.sqlite.org/pragma.html#pragma_table_info)

**output**<br>
`(column id, column name, data type, whether or not the column can be NULL, and the default value for the column)`

In [48]:
cursor.execute("PRAGMA table_info(airports)")
info = cursor.fetchall()
print(*info, sep = "\n")

(0, 'index', 'INTEGER', 0, None, 0)
(1, 'id', 'TEXT', 0, None, 0)
(2, 'name', 'TEXT', 0, None, 0)
(3, 'city', 'TEXT', 0, None, 0)
(4, 'country', 'TEXT', 0, None, 0)
(5, 'code', 'TEXT', 0, None, 0)
(6, 'icao', 'TEXT', 0, None, 0)
(7, 'latitude', 'TEXT', 0, None, 0)
(8, 'longitude', 'TEXT', 0, None, 0)
(9, 'altitude', 'TEXT', 0, None, 0)
(10, 'offset', 'TEXT', 0, None, 0)
(11, 'dst', 'TEXT', 0, None, 0)
(12, 'timezone', 'TEXT', 0, None, 0)

#### Making fetch happen

`.fetchall()` is how you get the query results out of the object.

You can also `.fetchone()` or `.fetchmany()`

**Task:** Get the descriptive data for airlines and routes tables

In [50]:
cursor.execute("PRAGMA table_info(airlines)")
info = cursor.fetchall()
print(*info, sep = "\n")

(0, 'index', 'INTEGER', 0, None, 0)
(1, 'id', 'TEXT', 0, None, 0)
(2, 'name', 'TEXT', 0, None, 0)
(3, 'alias', 'TEXT', 0, None, 0)
(4, 'iata', 'TEXT', 0, None, 0)
(5, 'icao', 'TEXT', 0, None, 0)
(6, 'callsign', 'TEXT', 0, None, 0)
(7, 'country', 'TEXT', 0, None, 0)
(8, 'active', 'TEXT', 0, None, 0)

In [54]:
cursor.execute('''select * from airlines;''').fetchmany(5)

[(0, '1', 'Private flight', '\\N', '-', None, None, None, 'Y'),
 (1, '2', '135 Airways', '\\N', None, 'GNL', 'GENERAL', 'United States', 'N'),
 (2, '3', '1Time Airline', '\\N', '1T', 'RNX', 'NEXTIME', 'South Africa', 'Y'),
 (3,
  '4',
  '2 Sqn No 1 Elementary Flying Training School',
  '\\N',
  None,
  'WYT',
  None,
  'United Kingdom',
  'N'),
 (4, '5', '213 Flight Unit', '\\N', None, 'TFU', None, 'Russia', 'N')]

In [51]:
cursor.execute("PRAGMA table_info(routes)")
info = cursor.fetchall()
print(*info, sep = "\n")

(0, 'index', 'INTEGER', 0, None, 0)
(1, 'airline', 'TEXT', 0, None, 0)
(2, 'airline_id', 'TEXT', 0, None, 0)
(3, 'source', 'TEXT', 0, None, 0)
(4, 'source_id', 'TEXT', 0, None, 0)
(5, 'dest', 'TEXT', 0, None, 0)
(6, 'dest_id', 'TEXT', 0, None, 0)
(7, 'codeshare', 'TEXT', 0, None, 0)
(8, 'stops', 'TEXT', 0, None, 0)
(9, 'equipment', 'TEXT', 0, None, 0)

In [55]:
cursor.execute('''select * from routes;''').fetchmany(5)

[(0, '2B', '410', 'AER', '2965', 'KZN', '2990', None, '0', 'CR2'),
 (1, '2B', '410', 'ASF', '2966', 'KZN', '2990', None, '0', 'CR2'),
 (2, '2B', '410', 'ASF', '2966', 'MRV', '2962', None, '0', 'CR2'),
 (3, '2B', '410', 'CEK', '2968', 'KZN', '2990', None, '0', 'CR2'),
 (4, '2B', '410', 'CEK', '2968', 'OVB', '4078', None, '0', 'CR2')]

***
## Goal 4: Use basic SQL commands 
- Construct SQL queries
- Use JOIN to merge tables along logical columns
- Grouping Data with SQL

### Construct SQL queries

**Select**

**From**

**Where**

**Order by**

**Limit**

#### Order matters!

#### Options for each:

**Select**:  `distinct`, using `as` to rename columns, single number aggregates

**From:** also uses aliasing with `as`

**Where**: equals is only one `=`, `between`, `in`, wildcards `%`, `AND`, `OR`, `NOT`

**Order by**: `asc` and `desc`

**Limit**:  #

**Task**: 
- Select only active airlines in the UK from the airlines table
- Select the unique list of countries with airports

In [57]:
cursor.execute('''select * from airlines where active = 'Y'; ''').fetchall()

[(0, '1', 'Private flight', '\\N', '-', None, None, None, 'Y'),
 (2, '3', '1Time Airline', '\\N', '1T', 'RNX', 'NEXTIME', 'South Africa', 'Y'),
 (9,
  '10',
  '40-Mile Air',
  '\\N',
  'Q5',
  'MLA',
  'MILE-AIR',
  'United States',
  'Y'),
 (12,
  '13',
  'Ansett Australia',
  '\\N',
  'AN',
  'AAA',
  'ANSETT',
  'Australia',
  'Y'),
 (13, '14', 'Abacus International', '\\N', '1B', None, None, 'Singapore', 'Y'),
 (20, '21', 'Aigle Azur', '\\N', 'ZI', 'AAF', 'AIGLE AZUR', 'France', 'Y'),
 (21,
  '22',
  'Aloha Airlines',
  '\\N',
  'AQ',
  'AAH',
  'ALOHA',
  'United States',
  'Y'),
 (23,
  '24',
  'American Airlines',
  '\\N',
  'AA',
  'AAL',
  'AMERICAN',
  'United States',
  'Y'),
 (27,
  '28',
  'Asiana Airlines',
  '\\N',
  'OZ',
  'AAR',
  'ASIANA',
  'Republic of Korea',
  'Y'),
 (28, '29', 'Askari Aviation', '\\N', '4K', 'AAS', 'AL-AAS', 'Pakistan', 'Y'),
 (31,
  '32',
  'Afriqiyah Airways',
  '\\N',
  '8U',
  'AAW',
  'AFRIQIYAH',
  'Libya',
  'Y'),
 (34,
  '35',
  'Allegiant Air',
  '\\N',
  'G4',
  'AAY',
  'ALLEGIANT',
  'United States',
  'Y'),
 (41,
  '42',
  'ABSA - Aerolinhas Brasileiras',
  '\\N',
  'M3',
  'TUS',
  'ABSA Cargo',
  'Brazil',
  'Y'),
 (54,
  '55',
  'Astral Aviation',
  '\\N',
  '8V',
  'ACP',
  'ASTRAL CARGO',
  'Kenya',
  'Y'),
 (67, '68', 'Air Tindi', '\\N', '8T', None, None, 'Canadian Territories', 'Y'),
 (71, '72', 'Ada Air', '\\N', 'ZY', 'ADE', 'ADA AIR', 'Albania', 'Y'),
 (82, '83', 'Adria Airways', '\\N', 'JP', 'ADR', 'ADRIA', 'Slovenia', 'Y'),
 (89, '90', 'Air Europa', '\\N', 'UX', 'AEA', 'EUROPA', 'Spain', 'Y'),
 (92, '93', 'Aero Benin', '\\N', 'EM', 'AEB', 'AEROBEN', 'Benin', 'Y'),
 (95, '96', 'Aegean Airlines', '\\N', 'A3', 'AEE', 'AEGEAN', 'Greece', 'Y'),
 (105, '106', 'Air Europe', '\\N', 'PE', 'AEL', 'AIR EUROPE', 'Italy', 'Y'),
 (108,
  '109',
  'Alaska Central Express',
  '\\N',
  'KO',
  'AER',
  'ACE AIR',
  'United States',
  'Y'),
 (109, '110', 'ACES Colombia', '\\N', None, 'AES', 'ACES', 'Colombia', 'Y'),
 (111,
  '112',
  'Astraeus',
  '\\N',
  '5W',
  'AEU',
  'FLYSTAR',
  'United Kingdom',
  'Y'),
 (113,
  '114',
  'Aerosvit Airlines',
  '\\N',
  'VV',
  'AEW',
  'AEROSVIT',
  'Ukraine',
  'Y'),
 (115, '116', 'Air Italy', '\\N', 'I9', 'AEY', 'AIR ITALY', 'Italy', 'Y'),
 (119,
  '120',
  'Alliance Airlines',
  '\\N',
  'QQ',
  'UTY',
  'UNITY',
  'Australia',
  'Y'),
 (124,
  '125',
  'Ariana Afghan Airlines',
  '\\N',
  'FG',
  'AFG',
  'ARIANA',
  'Afghanistan',
  'Y'),
 (129,
  '130',
  'Aeroflot Russian Airlines',
  '\\N',
  'SU',
  'AFL',
  'AEROFLOT',
  'Russia',
  'Y'),
 (131,
  '132',
  'Air Bosna',
  '\\N',
  'JA',
  'BON',
  'AIR BOSNA',
  'Bosnia and Herzegovina',
  'Y'),
 (136, '137', 'Air France', '\\N', 'AF', 'AFR', 'AIRFRANS', 'France', 'Y'),
 (138,
  '139',
  'Air Caledonie International',
  '\\N',
  'SB',
  'ACI',
  'AIRCALIN',
  'France',
  'Y'),
 (145, '146', 'Air Salone', '\\N', '2O', None, None, 'Sierra Leone', 'Y'),
 (148,
  '149',
  'Air Cargo Carriers',
  '\\N',
  '2Q',
  'SNC',
  'NIGHT CARGO',
  'United States',
  'Y'),
 (152, '153', 'Air Namibia', '\\N', 'SW', 'NMB', 'NAMIBIA', 'Namibia', 'Y'),
 (164, '165', 'Aerolitoral', '\\N', '5D', 'SLI', 'COSTERA', 'Mexico', 'Y'),
 (173,
  '174',
  'Air Glaciers',
  '\\N',
  '7T',
  'AGV',
  'AIR GLACIERS',
  'Switzerland',
  'Y'),
 (175, '176', 'Aviogenex', '\\N', None, 'AGX', 'GENEX', 'Serbia', 'Y'),
 (178, '179', 'Aeroper', '\\N', 'PL', 'PLI', 'Aeroperu', 'Peru', 'Y'),
 (179, '180', 'Atlas Blue', '\\N', '8A', 'BMM', 'ATLAS BLUE', 'Morocco', 'Y'),
 (196,
  '197',
  'Azerbaijan Airlines',
  '\\N',
  'J2',
  'AHY',
  'AZAL',
  'Azerbaijan',
  'Y'),
 (197, '198', 'Avies', '\\N', 'U3', 'AIA', 'AVIES', 'Estonia', 'Y'),
 (207, '208', 'Airblue', '\\N', 'ED', 'ABQ', 'PAKBLUE', 'Pakistan', 'Y'),
 (209,
  '210',
  'Airlift International',
  '\\N',
  None,
  'AIR',
  'AIRLIFT',
  'United States',
  'Y'),
 (213, '214', 'Air Berlin', '\\N', 'AB', 'BER', 'AIR BERLIN', 'Germany', 'Y'),
 (217,
  '218',
  'Air India Limited',
  '\\N',
  'AI',
  'AIC',
  'AIRINDIA',
  'India',
  'Y'),
 (219, '220', 'Air Bourbon', '\\N', 'ZB', 'BUB', 'BOURBON', 'Reunion', 'Y'),
 (220,
  '221',
  'Air Atlanta Icelandic',
  '\\N',
  'CC',
  'ABD',
  'ATLANTA',
  'Iceland',
  'Y'),
 (224,
  '225',
  'Air Tahiti Nui',
  '\\N',
  'TN',
  'THT',
  'TAHITI AIRLINES',
  'France',
  'Y'),
 (230,
  '231',
  'Arkia Israel Airlines',
  '\\N',
  'IZ',
  'AIZ',
  'ARKIA',
  'Israel',
  'Y'),
 (238, '239', 'Air Jamaica', '\\N', 'JM', 'AJM', 'JAMAICA', 'Jamaica', 'Y'),
 (239, '240', 'Air One', '\\N', 'AP', 'ADH', 'HERON', 'Italy', 'Y'),
 (240, '241', 'Air Sahara', '\\N', 'S2', 'RSH', 'SAHARA', 'India', 'Y'),
 (241, '242', 'Air Malta', '\\N', 'KM', 'AMC', 'AIR MALTA', 'Malta', 'Y'),
 (249, '250', 'Air Japan', '\\N', 'NQ', 'AJX', 'AIR JAPAN', 'Japan', 'Y'),
 (251,
  '252',
  'Air Korea Co. Ltd.',
  '\\N',
  None,
  'AKA',
  None,
  'Republic of Korea',
  'Y'),
 (262, '263', 'Air Kiribati', '\\N', '4A', 'AKL', None, 'Kiribati', 'Y'),
 (280,
  '281',
  'America West Airlines',
  '\\N',
  'HP',
  'AWE',
  'CACTUS',
  'United States',
  'Y'),
 (281,
  '282',
  'Air Wisconsin',
  '\\N',
  'ZW',
  'AWI',
  'AIR WISCONSIN',
  'United States',
  'Y'),
 (285,
  '286',
  'Tatarstan Airlines',
  '\\N',
  'U9',
  'TAK',
  'TATARSTAN',
  'Russia',
  'Y'),
 (286,
  '287',
  'Allegheny Commuter Airlines',
  '\\N',
  None,
  'ALO',
  'ALLEGHENY',
  'United States',
  'Y'),
 (294,
  '295',
  'Air Sunshine',
  '\\N',
  None,
  'RSI',
  'AIR SUNSHINE',
  'United States',
  'Y'),
 (298, '299', 'Air Libert', '\\N', 'VD', None, None, 'France', 'Y'),
 (305, '306', 'Air Malawi', '\\N', 'QM', 'AML', 'MALAWI', 'Malawi', 'Y'),
 (311, '312', 'Air Sicilia', '\\N', 'BM', None, None, 'Italy', 'Y'),
 (314,
  '315',
  'ATA Airlines',
  '\\N',
  None,
  'AMT',
  'AMTRAN',
  'United States',
  'Y'),
 (315, '316', 'Air Macau', '\\N', 'NX', 'AMU', 'AIR MACAO', 'Macao', 'Y'),
 (316, '317', 'AMC Airlines', '\\N', None, 'AMV', None, 'Egypt', 'Y'),
 (318,
  '319',
  'Air Seychelles',
  '\\N',
  'HM',
  'SEY',
  'SEYCHELLES',
  'Seychelles',
  'Y'),
 (320, '321', 'AeroMéxico', '\\N', 'AM', 'AMX', 'AEROMEXICO', 'Mexico', 'Y'),
 (323,
  '324',
  'All Nippon Airways',
  'ANA All Nippon Airways',
  'NH',
  'ANA',
  'ALL NIPPON',
  'Japan',
  'Y'),
 (326, '327', 'Air Nostrum', '\\N', 'YW', 'ANE', 'AIR NOSTRUM', 'Spain', 'Y'),
 (327,
  '328',
  'Air Niugini',
  '\\N',
  'PX',
  'ANG',
  'NUIGINI',
  'Papua New Guinea',
  'Y'),
 (328,
  '329',
  'Air Arabia',
  '\\N',
  'G9',
  'ABY',
  'ARABIA',
  'United Arab Emirates',
  'Y'),
 (329, '330', 'Air Canada', '\\N', 'AC', 'ACA', 'AIR CANADA', 'Canada', 'Y'),
 (332, '333', 'Air Baltic', '\\N', 'BT', 'BTI', 'AIRBALTIC', 'Latvia', 'Y'),
 (335, '336', 'Air Nippon', '\\N', 'EL', 'ANK', 'ANK AIR', 'Japan', 'Y'),
 (337, '338', 'Airnorth', '\\N', 'TL', 'ANO', 'TOPEND', 'Australia', 'Y'),
 (340,
  '341',
  'Air North Charter - Canada',
  '\\N',
  '4N',
  'ANT',
  'AIR NORTH',
  'Canada',
  'Y'),
 (344,
  '345',
  'Air New Zealand',
  '\\N',
  'NZ',
  'ANZ',
  'NEW ZEALAND',
  'New Zealand',
  'Y'),
 (370,
  '371',
  'Alitalia Express',
  '\\N',
  'XM',
  'SMX',
  'ALIEXPRESS',
  'Italy',
  'Y'),
 (385, '386', 'Aero Flight', '\\N', 'GV', 'ARF', 'Aero Fox', 'Germany', 'Y'),
 (396, '397', 'Arrow Air', '\\N', 'JW', 'APW', 'BIG A', 'United States', 'Y'),
 (409, '410', 'Aerocondor', '\\N', '2B', 'ARD', 'AEROCONDOR', 'Portugal', 'Y'),
 (410,
  '411',
  'Aires',
  '\\N',
  '4C',
  'ARE',
  ' Aerovias de Integracion Regional',
  ' S.A.',
  'Y'),
 (411,
  '412',
  'Aerolineas Argentinas',
  '\\N',
  'AR',
  'ARG',
  'ARGENTINA',
  'Argentina',
  'Y'),
 (438, '439', 'Alaska Airlines', '\\N', 'AS', 'ASA', ' Inc.', 'ALASKA', 'Y'),
 (441, '442', 'Air Sinai', '\\N', '4D', 'ASD', 'AIR SINAI', 'Egypt', 'Y'),
 (451,
  '452',
  'Atlantic Southeast Airlines',
  '\\N',
  'EV',
  'ASQ',
  'ACEY',
  'United States',
  'Y'),
 (461,
  '462',
  'Astrakhan Airlines',
  '\\N',
  'OB',
  'ASZ',
  'AIR ASTRAKHAN',
  'Russia',
  'Y'),
 (464, '465', 'Air Tanzania', '\\N', 'TC', 'ATC', 'TANZANIA', 'Tanzania', 'Y'),
 (469,
  '470',
  'Air Burkina',
  '\\N',
  '2J',
  'VBW',
  'BURKINA',
  'Burkina Faso',
  'Y'),
 (475,
  '476',
  'Airlines Of Tasmania',
  '\\N',
  'FO',
  'ATM',
  'AIRTAS',
  'Australia',
  'Y'),
 (476, '477', 'Air Saint Pierre', '\\N', 'PJ', 'SPM', None, 'France', 'Y'),
 (490,
  '491',
  'Austrian Airlines',
  '\\N',
  'OS',
  'AUA',
  'AUSTRIAN',
  'Austria',
  'Y'),
 (491,
  '492',
  'Air Southwest',
  '\\N',
  None,
  'WOW',
  'SWALLOW',
  'United Kingdom',
  'Y'),
 (492,
  '493',
  'Augsburg Airways',
  '\\N',
  'IQ',
  'AUB',
  'AUGSBURG-AIR',
  'Germany',
  'Y'),
 (496, '497', 'ATUR', '\\N', None, 'TUR', None, 'Ecuador', 'Y'),
 (501,
  '502',
  'Abu Dhabi Amiri Flight',
  '\\N',
  'MO',
  'AUH',
  'SULTAN',
  'United Arab Emirates',
  'Y'),
 (502, '503', 'Aeroflot-Nord', '\\N', '5N', 'AUL', 'DVINA', 'Russia', 'Y'),
 (507,
  '508',
  'Aurigny Air Services',
  '\\N',
  'GR',
  'AUR',
  'AYLINE',
  'United Kingdom',
  'Y'),
 (509,
  '510',
  'Austral Lineas Aereas',
  '\\N',
  'AU',
  'AUT',
  'AUSTRAL',
  'Argentina',
  'Y'),
 (514,
  '515',
  'Avianca - Aerovias Nacionales de Colombia',
  '\\N',
  'AV',
  'AVA',
  ' S.A.',
  'AVIANCA',
  'Y'),
 (523, '524', 'Air Vanuatu', '\\N', 'NF', 'AVN', 'AIR VAN', 'Vanuatu', 'Y'),
 (542,
  '543',
  'Air Bangladesh',
  '\\N',
  'B9',
  'BGD',
  'AIR BANGLA',
  'Bangladesh',
  'Y'),
 (546,
  '547',
  'Air Mediterranee',
  '\\N',
  'DR',
  'BIE',
  'MEDITERRANEE',
  'France',
  'Y'),
 (550, '551', 'Air Moorea', '\\N', None, 'TAH', 'AIR MOOREA', 'France', 'Y'),
 (562, '563', 'Aeroline GmbH', '\\N', '7E', 'AWU', 'SYLT-AIR', 'Germany', 'Y'),
 (564,
  '565',
  'Air Wales',
  '\\N',
  '6G',
  'AWW',
  'RED DRAGON',
  'United Kingdom',
  'Y'),
 (566,
  '567',
  'Air Caraïbes',
  '\\N',
  'TX',
  'FWI',
  'FRENCH WEST',
  'France',
  'Y'),
 (568,
  '569',
  'Air India Express',
  '\\N',
  'IX',
  'AXB',
  'EXPRESS INDIA',
  'India',
  'Y'),
 (574,
  '575',
  'Air Exel',
  '\\N',
  'XT',
  'AXL',
  'EXEL COMMUTER',
  'Netherlands',
  'Y'),
 (575,
  '576',
  'AirAsia',
  'Air Asia',
  'AK',
  'AXM',
  'ASIAN EXPRESS',
  'Malaysia',
  'Y'),
 (594,
  '595',
  'Atlant-Soyuz Airlines',
  '\\N',
  '3G',
  'AYZ',
  'ATLANT-SOYUZ',
  'Russia',
  'Y'),
 (595, '596', 'Alitalia', '\\N', 'AZ', 'AZA', 'ALITALIA', 'Italy', 'Y'),
 (602, '603', 'Amaszonas', '\\N', 'Z8', 'AZN', None, 'Bolivia', 'Y'),
 (607,
  '608',
  'Air Zimbabwe',
  '\\N',
  'UM',
  'AZW',
  'AIR ZIMBABWE',
  'Zimbabwe',
  'Y'),
 (621,
  '622',
  'Aserca Airlines',
  '\\N',
  'R7',
  'OCA',
  'AROSCA',
  'Venezuela',
  'Y'),
 (640,
  '641',
  'Rossiya-Russian Airlines',
  'Pulkovo Aviation Enterprise',
  'FV',
  'SDM',
  'PULKOVO',
  'Russia',
  'Y'),
 (658,
  '659',
  'American Eagle Airlines',
  '\\N',
  'MQ',
  'EGF',
  'EAGLE FLIGHT',
  'United States',
  'Y'),
 (664,
  '665',
  'AD Aviation',
  '\\N',
  None,
  'VUE',
  'FLIGHTVUE',
  'United Kingdom',
  'Y'),
 (681,
  '682',
  'Air Ivoire',
  '\\N',
  'VU',
  'VUN',
  'AIRIVOIRE',
  'Ivory Coast',
  'Y'),
 (682, '683', 'Air Botswana', '\\N', 'BP', 'BOT', 'BOTSWANA', 'Botswana', 'Y'),
 (689, '690', 'Air Foyle', '\\N', 'GS', 'UPA', 'FOYLE', 'United Kingdom', 'Y'),
 (691,
  '692',
  'Air Tahiti',
  '\\N',
  'VT',
  'VTA',
  'AIR TAHITI',
  'French Polynesia',
  'Y'),
 (694, '695', 'Air VIA', '\\N', 'VL', 'VIM', None, 'Bulgaria', 'Y'),
 (714, '715', 'Africa West', '\\N', 'FK', 'WTA', 'WEST TOGO', 'Togo', 'Y'),
 (723,
  '724',
  'ATRAN Cargo Airlines',
  '\\N',
  'V8',
  'VAS',
  'ATRAN',
  'Russian Federation',
  'Y'),
 (750, '751', 'Air China', '\\N', 'CA', 'CCA', 'AIR CHINA', 'China', 'Y'),
 (752,
  '753',
  'Aero Condor Peru',
  '\\N',
  'Q6',
  'CDP',
  'CONDOR-PERU',
  'Peru',
  'Y'),
 (786,
  '787',
  'Air Chathams',
  '\\N',
  'CV',
  'CVA',
  'CHATHAM',
  'New Zealand',
  'Y'),
 (787,
  '788',
  'Air Marshall Islands',
  '\\N',
  'CW',
  'CWM',
  'AIR MARSHALLS',
  'Marshall Islands',
  'Y'),
 (791,
  '792',
  'Access Air',
  '\\N',
  'ZA',
  'CYD',
  'CYCLONE',
  'United States',
  'Y'),
 (793,
  '794',
  'Air Algerie',
  '\\N',
  'AH',
  'DAH',
  'AIR ALGERIE',
  'Algeria',
  'Y'),
 (799, '800', 'Adam Air', '\\N', 'KI', 'DHI', 'ADAM SKY', 'Indonesia', 'Y'),
 (806, '807', 'Air Dolomiti', '\\N', 'EN', 'DLA', 'DOLOMOTI', 'Italy', 'Y'),
 (815, '816', 'Aeroflot-Don', '\\N', 'D9', 'DNV', 'DONAVIA', 'Russia', 'Y'),
 (816, '817', 'Air Madrid', '\\N', 'NM', 'DRD', 'ALADA AIR', 'Spain', 'Y'),
 (836, '837', 'Aer Lingus', '\\N', 'EI', 'EIN', 'SHAMROCK', 'Ireland', 'Y'),
 (875,
  '876',
  'Air Finland',
  '\\N',
  'OF',
  'FIF',
  'AIR FINLAND',
  'Finland',
  'Y'),
 (877, '878', 'Airfix Aviation', '\\N', None, 'FIX', 'AIRFIX', 'Finland', 'Y'),
 (878, '879', 'Air Pacific', '\\N', 'FJ', 'FJI', 'PACIFIC', 'Fiji', 'Y'),
 (880,
  '881',
  'Atlantic Airways',
  '\\N',
  'RC',
  'FLI',
  'FAROELINE',
  'Faroe Islands',
  'Y'),
 (881,
  '882',
  'Air Florida',
  '\\N',
  'QH',
  'FLZ',
  'AIR FLORIDA',
  'United States',
  'Y'),
 (895, '896', 'Air Iceland', '\\N', 'NY', 'FXI', 'FAXI', 'Iceland', 'Y'),
 (896,
  '897',
  'Air Philippines',
  '\\N',
  '2P',
  'GAP',
  'ORIENT PACIFIC',
  'Philippines',
  'Y'),
 (908,
  '909',
  'Air Guinee Express',
  '\\N',
  '2U',
  'GIP',
  'FUTURE EXPRESS',
  'Guinea',
  'Y'),
 (920,
  '921',
  'Air Greenland',
  '\\N',
  'GL',
  'GRL',
  'GREENLAND',
  'Denmark',
  'Y'),
 (927, '928', 'Atlas Air', '\\N', '5Y', 'GTI', 'GIANT', 'United States', 'Y'),
 (930,
  '931',
  'Air Guyane',
  '\\N',
  'GG',
  'GUY',
  'GREEN BIRD',
  'French Guiana',
  'Y'),
 (969, '970', 'Air Bagan', '\\N', 'W9', 'JAB', 'AIR BAGAN', 'Myanmar', 'Y'),
 (982, '983', 'Air Canada Jazz', '\\N', 'QK', 'JZA', 'JAZZ', 'Canada', 'Y'),
 (994, '995', 'Atlasjet', '\\N', 'KK', 'KKK', 'ATLASJET', 'Turkey', 'Y'),
 (997,
  '998',
  'Air Koryo',
  '\\N',
  'JS',
  'KOR',
  'AIR KORYO',
  "Democratic People's Republic of Korea",
  'Y'),
 (1005,
  '1006',
  'Air Astana',
  '\\N',
  'KC',
  'KZR',
  'ASTANALINE',
  'Kazakhstan',
  'Y'),
 (1007,
  '1008',
  'Albanian Airlines',
  '\\N',
  'LV',
  'LBC',
  'ALBANIAN',
  'Albania',
  'Y'),
 (1016, '1017', 'Air Alfa', '\\N', None, 'LFA', None, 'Turkey', 'Y'),
 (1033, '1034', 'Aerolane', '\\N', 'XL', 'LNE', 'LAN ECUADOR', 'Ecuador', 'Y'),
 (1047,
  '1048',
  'Atlantis European Airways',
  '\\N',
  'TD',
  'LUR',
  None,
  'Armenia',
  'Y'),
 (1051, '1052', 'Air Luxor', '\\N', 'LK', 'LXR', 'AIRLUXOR', 'Portugal', 'Y'),
 (1056,
  '1057',
  'Air Mauritius',
  '\\N',
  'MK',
  'MAU',
  'AIRMAURITIUS',
  'Mauritius',
  'Y'),
 (1065,
  '1066',
  'Air Madagascar',
  '\\N',
  'MD',
  'MDG',
  'AIR MADAGASCAR',
  'Madagascar',
  'Y'),
 (1072,
  '1073',
  'Air Moldova',
  '\\N',
  '9U',
  'MLD',
  'AIR MOLDOVA',
  'Moldova',
  'Y'),
 (1086,
  '1087',
  'Air Plus Comet',
  '\\N',
  'A7',
  'MPD',
  'RED COMET',
  'Spain',
  'Y'),
 (1107, '1109', 'Astair', '\\N', '8D', None, None, 'Russian Federation', 'Y'),
 (1114,
  '1116',
  'Aero Contractors',
  '\\N',
  'AJ',
  'NIG',
  'AEROLINE',
  'Nigeria',
  'Y'),
 (1141,
  '1143',
  'Aeropelican Air Services',
  '\\N',
  'OT',
  'PEL',
  'PELICAN',
  'Australia',
  'Y'),
 (1186, '1188', 'Aer Arann', '\\N', 'RE', 'REA', 'AER ARANN', 'Ireland', 'Y'),
 (1189, '1191', 'Air Austral', '\\N', 'UU', 'REU', 'REUNION', 'France', 'Y'),
 (1198,
  '1200',
  'Asian Spirit',
  '\\N',
  '6K',
  'RIT',
  'ASIAN SPIRIT',
  'Philippines',
  'Y'),
 (1200,
  '1202',
  'Air Afrique',
  '\\N',
  'RK',
  'RKA',
  'AIRAFRIC',
  'Ivory Coast',
  'Y'),
 (1201, '1203', 'Airlinair', '\\N', 'A5', 'RLA', 'AIRLINAIR', 'France', 'Y'),
 (1204,
  '1206',
  'Aero Lanka',
  '\\N',
  'QL',
  'RLN',
  'AERO LANKA',
  'Sri Lanka',
  'Y'),
 (1211,
  '1213',
  'Air Salone',
  '\\N',
  '20',
  'RNE',
  'AIR SALONE',
  'Sierra Leone',
  'Y'),
 (1214, '1216', 'Armavia', '\\N', 'U8', 'RNV', 'ARMAVIA', 'Armenia', 'Y'),
 (1222,
  '1224',
  'AeroRep',
  '\\N',
  'P5',
  'RPB',
  'AEROREPUBLICA',
  'Colombia',
  'Y'),
 (1228,
  '1230',
  'Aero-Service',
  '\\N',
  'BF',
  'RSR',
  'CONGOSERV',
  'Republic of the Congo',
  'Y'),
 (1229, '1231', 'Aerosur', '\\N', '5L', 'RSU', 'AEROSUR', 'Bolivia', 'Y'),
 (1230, '1232', 'Aeronorte', '\\N', None, 'RTE', 'LUZAVIA', 'Portugal', 'Y'),
 (1264,
  '1266',
  'Avient Aviation',
  '\\N',
  'Z3',
  'SMJ',
  'AVAVIA',
  'Zimbabwe',
  'Y'),
 (1285,
  '1287',
  'Aircompany Yakutia',
  '\\N',
  'R3',
  'SYL',
  'AIR YAKUTIA',
  'Russia',
  'Y'),
 (1288, '1290', 'Aeromar', '\\N', 'VW', 'TAO', 'TRANS-AEROMAR', 'Mexico', 'Y'),
 (1297, '1299', 'Arkefly', '\\N', 'OR', 'TFL', 'ARKEFLY', 'Netherlands', 'Y'),
 (1306,
  '1308',
  'Airlines PNG',
  '\\N',
  'CG',
  'TOK',
  'BALUS',
  'Papua New Guinea',
  'Y'),
 (1314,
  '1316',
  'AirTran Airways',
  '\\N',
  'FL',
  'TRS',
  'CITRUS',
  'United States',
  'Y'),
 (1315, '1317', 'Air Transat', '\\N', 'TS', 'TSC', 'TRANSAT', 'Canada', 'Y'),
 (1320,
  '1322',
  'Avialeasing Aviation Company',
  '\\N',
  'EC',
  'TWN',
  'TWINARROW',
  'Uzbekistan',
  'Y'),
 (1324,
  '1326',
  'Tyrolean Airways',
  '\\N',
  'VO',
  'TYR',
  'TYROLEAN',
  'Austria',
  'Y'),
 (1336,
  '1338',
  'Aerolineas Galapagos (Aerogal)',
  '\\N',
  '2K',
  'GLG',
  'AEROGAL',
  'Ecuador',
  'Y'),
 (1338,
  '1340',
  'Alrosa Mirny Air Enterprise',
  '\\N',
  '6R',
  'DRU',
  'MIRNY',
  'Russia',
  'Y'),
 (1353,
  '1355',
  'British Airways',
  '\\N',
  'BA',
  'BAW',
  'SPEEDBIRD',
  'United Kingdom',
  'Y'),
 (1357,
  '1359',
  'Biman Bangladesh Airlines',
  '\\N',
  'BG',
  'BBC',
  'BANGLADESH',
  'Bangladesh',
  'Y'),
 (1399,
  '1401',
  'Belair Airlines',
  '\\N',
  '4T',
  'BHP',
  'BELAIR',
  'Switzerland',
  'Y'),
 (1401, '1403', 'Bahamasair', '\\N', 'UP', 'BHS', 'BAHAMAS', 'Bahamas', 'Y'),
 (1404,
  '1406',
  'Balkan Bulgarian Airlines',
  '\\N',
  'LZ',
  None,
  None,
  None,
  'Y'),
 (1409,
  '1411',
  'British International Helicopters',
  '\\N',
  'BS',
  'BIH',
  'BRINTEL',
  'United Kingdom',
  'Y'),
 (1418,
  '1420',
  'BF-Lento OY',
  '\\N',
  None,
  'BKF',
  'BAKERFLIGHT',
  'Finland',
  'Y'),
 (1420,
  '1422',
  'Bangkok Airways',
  '\\N',
  'PG',
  'BKP',
  'BANGKOK AIR',
  'Thailand',
  'Y'),
 (1425, '1427', 'Blue1', '\\N', 'KF', 'BLF', 'BLUEFIN', 'Finland', 'Y'),
 (1429,
  '1431',
  'Baltic Airlines',
  '\\N',
  None,
  'BLL',
  'BALTIC AIRLINES',
  'Russia',
  'Y'),
 (1432,
  '1434',
  'Bearskin Lake Air Service',
  '\\N',
  'JV',
  'BLS',
  'BEARSKIN',
  'Canada',
  'Y'),
 (1434,
  '1436',
  'Bellview Airlines',
  '\\N',
  'B3',
  'BLV',
  'BELLVIEW AIRLINES',
  'Nigeria',
  'Y'),
 (1435,
  '1437',
  'bmi',
  'bmi British Midland',
  'BD',
  'BMA',
  'MIDLAND',
  'United Kingdom',
  'Y'),
 (1439, '1441', 'bmibaby', '\\N', 'WW', 'BMI', 'BABY', 'United Kingdom', 'Y'),
 (1440,
  '1442',
  'Bemidji Airlines',
  '\\N',
  'CH',
  'BMJ',
  'BEMIDJI',
  'United States',
  'Y'),
 (1443,
  '1445',
  'British Midland Regional',
  '\\N',
  None,
  'BMR',
  None,
  'United Kingdom',
  'Y'),
 (1461,
  '1463',
  'Blue Panorama Airlines',
  '\\N',
  'BV',
  'BPA',
  'BLUE PANOROMA',
  'Italy',
  'Y'),
 (1464,
  '1466',
  'Budapest Aircraft Services/Manx2',
  '\\N',
  None,
  'BPS',
  'BASE',
  'Hungary',
  'Y'),
 (1470,
  '1472',
  'Bering Air',
  '\\N',
  '8E',
  'BRG',
  'BERING AIR',
  'United States',
  'Y'),
 (1474,
  '1476',
  'Brazilian Air Force',
  '\\N',
  None,
  'BRS',
  'BRAZILIAN AIR FORCE',
  'Brazil',
  'Y'),
 (1476,
  '1478',
  'Belavia Belarusian Airlines',
  '\\N',
  'B2',
  'BRU',
  'BELARUS AVIA',
  'Belarus',
  'Y'),
 (1498,
  '1500',
  'Metro Batavia',
  '\\N',
  '7P',
  'BTV',
  'BATAVIA',
  'Indonesia',
  'Y'),
 (1506, '1508', 'Berjaya Air', '\\N', 'J8', 'BVT', 'BERJAYA', 'Malaysia', 'Y'),
 (1508,
  '1510',
  'Blue Wings',
  '\\N',
  'QW',
  'BWG',
  'BLUE WINGS',
  'Germany',
  'Y'),
 (1521, '1523', 'Brit Air', '\\N', 'DB', 'BZH', 'BRITAIR', 'France', 'Y'),
 (1529,
  '1531',
  'Brussels Airlines',
  'SN Brussels Airlines',
  'SN',
  'DAT',

In [58]:
cursor.execute('''select distinct country from airports;''').fetchall()

[('Papua New Guinea',),
 ('Greenland',),
 ('Iceland',),
 ('Canada',),
 ('Algeria',),
 ('Benin',),
 ('Burkina Faso',),
 ('Ghana',),
 ("Cote d'Ivoire",),
 ('Nigeria',),
 ('Niger',),
 ('Tunisia',),
 ('Togo',),
 ('Belgium',),
 ('Germany',),
 ('United States',),
 ('Estonia',),
 ('Finland',),
 ('United Kingdom',),
 ('Guernsey',),
 ('Jersey',),
 ('Isle of Man',),
 ('Falkland Islands',),
 ('Netherlands',),
 ('Ireland',),
 ('Denmark',),
 ('Faroe Islands',),
 ('Luxembourg',),
 ('Norway',),
 ('Poland',),
 ('Sweden',),
 ('South Africa',),
 ('Botswana',),
 ('Congo (Brazzaville)',),
 ('Congo (Kinshasa)',),
 ('Swaziland',),
 ('Central African Republic',),
 ('Equatorial Guinea',),
 ('Saint Helena',),
 ('Mauritius',),
 ('British Indian Ocean Territory',),
 ('Cameroon',),
 ('Zambia',),
 ('Comoros',),
 ('Mayotte',),
 ('Reunion',),
 ('Madagascar',),
 ('Angola',),
 ('Puerto Rico',),
 ('Gabon',),
 ('Sao Tome and Principe',),
 ('Mozambique',),
 ('Seychelles',),
 ('Chad',),
 ('Zimbabwe',),
 ('Malawi',),
 ('Lesotho',),
 ('Mali',),
 ('Gambia',),
 ('Spain',),
 ('Sierra Leone',),
 ('Guinea-Bissau',),
 ('Liberia',),
 ('Morocco',),
 ('Senegal',),
 ('Mauritania',),
 ('Guinea',),
 ('Cape Verde',),
 ('Ethiopia',),
 ('Maldives',),
 ('Burundi',),
 ('Somalia',),
 ('Egypt',),
 ('Kenya',),
 ('Libya',),
 ('Rwanda',),
 ('Sudan',),
 ('South Sudan',),
 ('Tanzania',),
 ('Uganda',),
 ('Albania',),
 ('Bulgaria',),
 ('Cyprus',),
 ('Croatia',),
 ('Greece',),
 ('France',),
 ('Saint Pierre and Miquelon',),
 ('Hungary',),
 ('Italy',),
 ('Slovenia',),
 ('Czech Republic',),
 ('Israel',),
 ('Malta',),
 ('Austria',),
 ('Portugal',),
 ('Bosnia and Herzegovina',),
 ('Romania',),
 ('Switzerland',),
 ('Turkey',),
 ('Moldova',),
 ('Macedonia',),
 ('Gibraltar',),
 ('Serbia',),
 ('Montenegro',),
 ('Slovakia',),
 ('Turks and Caicos Islands',),
 ('Dominican Republic',),
 ('Guatemala',),
 ('Honduras',),
 ('Jamaica',),
 ('Mexico',),
 ('Nicaragua',),
 ('Panama',),
 ('Costa Rica',),
 ('El Salvador',),
 ('Haiti',),
 ('Cuba',),
 ('Cayman Islands',),
 ('Bahamas',),
 ('Belize',),
 ('Cook Islands',),
 ('Fiji',),
 ('Tonga',),
 ('Kiribati',),
 ('Australia',),
 ('Wallis and Futuna',),
 ('Samoa',),
 ('American Samoa',),
 ('French Polynesia',),
 ('Vanuatu',),
 ('New Caledonia',),
 ('New Zealand',),
 ('Antarctica',),
 ('Afghanistan',),
 ('Bahrain',),
 ('Saudi Arabia',),
 ('Iran',),
 ('Argentina',),
 ('Jordan',),
 ('West Bank',),
 ('Kuwait',),
 ('Lebanon',),
 ('United Arab Emirates',),
 ('Oman',),
 ('Pakistan',),
 ('Iraq',),
 ('Syria',),
 ('Qatar',),
 ('Northern Mariana Islands',),
 ('Guam',),
 ('Marshall Islands',),
 ('Midway Islands',),
 ('Micronesia',),
 ('Palau',),
 ('Taiwan',),
 ('Japan',),
 ('South Korea',),
 ('Philippines',),
 ('Turkmenistan',),
 ('Brazil',),
 ('Chile',),
 ('Ecuador',),
 ('Paraguay',),
 ('Colombia',),
 ('Bolivia',),
 ('Suriname',),
 ('French Guiana',),
 ('Peru',),
 ('Uruguay',),
 ('Venezuela',),
 ('Guyana',),
 ('Antigua and Barbuda',),
 ('Barbados',),
 ('Dominica',),
 ('Martinique',),
 ('Guadeloupe',),
 ('Grenada',),
 ('Virgin Islands',),
 ('Saint Kitts and Nevis',),
 ('Saint Lucia',),
 ('Aruba',),
 ('Netherlands Antilles',),
 ('Anguilla',),
 ('Trinidad and Tobago',),
 ('British Virgin Islands',),
 ('Saint Vincent and the Grenadines',),
 ('Kazakhstan',),
 ('Kyrgyzstan',),
 ('Azerbaijan',),
 ('Russia',),
 ('Ukraine',),
 ('Belarus',),
 ('Tajikistan',),
 ('Uzbekistan',),
 ('India',),
 ('Sri Lanka',),
 ('Cambodia',),
 ('Bangladesh',),
 ('Hong Kong',),
 ('Laos',),
 ('Macau',),
 ('Nepal',),
 ('Bhutan',),
 ('Thailand',),
 ('Indonesia',),
 ('Vietnam',),
 ('Burma',),
 ('Malaysia',),
 ('Brunei',),
 ('East Timor',),
 ('Singapore',),
 ('Christmas Island',),
 ('Norfolk Island',),
 ('China',),
 ('Korea',),
 ('Mongolia',),
 ('Latvia',),
 ('Lithuania',),
 ('Armenia',),
 ('Eritrea',),
 ('Palestine',),
 ('Yemen',),
 ('Georgia',),
 ('Bermuda',),
 ('Solomon Islands',),
 ('Nauru',),
 ('Tuvalu',),
 ('Namibia',),
 ('Djibouti',),
 ('Montserrat',),
 ('Monaco',),
 ('Johnston Atoll',),
 ('Niue',),
 ('Western Sahara',),
 ('Cocos (Keeling) Islands',),
 ('South Georgia and the Islands',),
 ('Myanmar',),
 ('Svalbard',),
 ('North Korea',),
 ('Wake Island',)]

### SQL Joins

SQL joins can be used to both **add** data to a table and **remove** data from a table.

![venn](img/venn.png)

**Task** Write a query that will join the latitude and longitude data from the airports table to the information on the routes table

In [60]:
cursor.execute('''select source, latitude, longitude from routes r left join airports a on r.source = a.code; ''').fetchall()

[('AER', '43.449928', '39.956589'),
 ('ASF', '46.283333', '48.006278'),
 ('ASF', '46.283333', '48.006278'),
 ('CEK', '55.305836', '61.503333'),
 ('CEK', '55.305836', '61.503333'),
 ('DME', '55.408611', '37.906111'),
 ('DME', '55.408611', '37.906111'),
 ('DME', '55.408611', '37.906111'),
 ('DME', '55.408611', '37.906111'),
 ('EGO', '50.6438', '36.5901'),
 ('EGO', '50.6438', '36.5901'),
 ('GYD', '40.4675', '50.046667'),
 ('KGD', '54.89005', '20.592633'),
 ('KZN', '55.606186', '49.278728'),
 ('KZN', '55.606186', '49.278728'),
 ('KZN', '55.606186', '49.278728'),
 ('KZN', '55.606186', '49.278728'),
 ('KZN', '55.606186', '49.278728'),
 ('KZN', '55.606186', '49.278728'),
 ('KZN', '55.606186', '49.278728'),
 ('LED', '59.800292', '30.262503'),
 ('LED', '59.800292', '30.262503'),
 ('LED', '59.800292', '30.262503'),
 ('MRV', '44.225072', '43.081889'),
 ('NBC', '55.34', '52.06'),
 ('NBC', '55.34', '52.06'),
 ('NBC', '55.34', '52.06'),
 ('NBC', '55.34', '52.06'),
 ('NJC', '60.949272', '76.483617'),
 ('NJC', '60.949272', '76.483617'),
 ('NUX', '66.041811', '76.313938'),
 ('OVB', '55.012622', '82.650656'),
 ('OVB', '55.012622', '82.650656'),
 ('SVX', '56.743108', '60.802728'),
 ('SVX', '56.743108', '60.802728'),
 ('SVX', '56.743108', '60.802728'),
 ('SVX', '56.743108', '60.802728'),
 ('SVX', '56.743108', '60.802728'),
 ('TGK', None, None),
 ('UUA', '54.64', '52.8017'),
 ('UUA', '54.64', '52.8017'),
 ('UUA', '54.64', '52.8017'),
 ('BTK', '56.370556', '101.698331'),
 ('BTK', '56.370556', '101.698331'),
 ('CEK', '55.305836', '61.503333'),
 ('HTA', '52.026317', '113.305556'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('IKT', '52.268028', '104.388975'),
 ('KCK', None, None),
 ('MJZ', '62.534689', '114.038928'),
 ('ODO', '57.5137', '114.1348'),
 ('OVB', '55.012622', '82.650656'),
 ('OVB', '55.012622', '82.650656'),
 ('OVB', '55.012622', '82.650656'),
 ('UKX', '56.85', '105.7167'),
 ('ULK', '60.723', '114.825'),
 ('YKS', '62.09325', '129.770672'),
 ('AYP', '-13.154819', '-74.204417'),
 ('CUZ', '-13.535722', '-71.938781'),
 ('CUZ', '-13.535722', '-71.938781'),
 ('HUU', '-9.878811', '-76.204797'),
 ('IQT', '-3.784739', '-73.308806'),
 ('IQT', '-3.784739', '-73.308806'),
 ('LIM', '-12.021889', '-77.114319'),
 ('LIM', '-12.021889', '-77.114319'),
 ('LIM', '-12.021889', '-77.114319'),
 ('LIM', '-12.021889', '-77.114319'),
 ('LIM', '-12.021889', '-77.114319'),
 ('PCL', '-8.377939', '-74.574297'),
 ('PCL', '-8.377939', '-74.574297'),
 ('PCL', '-8.377939', '-74.574297'),
 ('PEM', '-12.613611', '-69.228611'),
 ('TPP', '-6.508742', '-76.373247'),
 ('TPP', '-6.508742', '-76.373247'),
 ('TPP', '-6.508742', '-76.373247'),
 ('ABJ', '5.261386', '-3.926294'),
 ('ABJ', '5.261386', '-3.926294'),
 ('ACC', '5.605186', '-0.166786'),
 ('BKO', '12.533544', '-7.949944'),
 ('BKO', '12.533544', '-7.949944'),
 ('BKO', '12.533544', '-7.949944'),
 ('BOY', '11.160056', '-4.330969'),
 ('BOY', '11.160056', '-4.330969'),
 ('COO', '6.357228', '2.384353'),
 ('COO', '6.357228', '2.384353'),
 ('DKR', '14.739708', '-17.490225'),
 ('DKR', '14.739708', '-17.490225'),
 ('LFW', '6.165611', '1.254511'),
 ('NIM', '13.481547', '2.183614'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('OUA', '12.353194', '-1.512417'),
 ('BOG', '4.701594', '-74.146947'),
 ('BOG', '4.701594', '-74.146947'),
 ('CLO', '3.543222', '-76.381583'),
 ('GYE', '-2.157419', '-79.883558'),
 ('GYE', '-2.157419', '-79.883558'),
 ('GYE', '-2.157419', '-79.883558'),
 ('GYE', '-2.157419', '-79.883558'),
 ('OCC', '-0.462886', '-76.986842'),
 ('SCY', '-0.910206', '-89.61745'),
 ('UIO', '-0.141144', '-78.488214'),
 ('UIO', '-0.141144', '-78.488214'),
 ('UIO', '-0.141144', '-78.488214'),
 ('BDS', '40.657633', '17.947033'),
 ('BOD', '44.828335', '-0.715556'),
 ('BRS', '51.382669', '-2.719089'),
 ('GVA', '46.238064', '6.10895'),
 ('LCA', '34.875117', '33.62485'),
 ('LPA', '27.931886', '-15.386586'),
 ('RMF', '25.557111', '34.583711'),
 ('TFS', '28.044475', '-16.572489'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('AJR', '65.590278', '19.281944'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('ARN', '59.651944', '17.918611'),
 ('GEV', '67.132408', '20.814636'),
 ('GEV', '67.132408', '20.814636'),
 ('HAD', '56.691128', '12.820211'),
 ('HAD', '56.691128', '12.820211'),
 ('HAD', '56.691128', '12.820211'),
 ('HMV', '65.806111', '15.082778'),
 ('JKG', '57.757594', '14.068731'),
 ('JKG', '57.757594', '14.068731'),
 ('KOK', '63.721172', '23.143131'),
 ('KRF', '63.048597', '17.768856'),
 ('KRF', '63.048597', '17.768856'),
 ('KSD', '59.4447', '13.3374'),
 ('LYC', '64.548322', '18.716219'),
 ('LYC', '64.548322', '18.716219'),
 ('MHQ', '60.122203', '19.898156'),
 ('MHQ', '60.122203', '19.898156'),
 ('OER', '63.408339', '18.990039'),
 ('OSL', '60.193917', '11.100361'),
 ('POR', '61.461686', '21.799983'),
 ('POR', '61.461686', '21.799983'),
 ('TKU', '60.514142', '22.262808'),
 ('TRF', '59.186703', '10.258628'),
 ('VBY', '57.662797', '18.346211'),
 ('VHM', '64.579083', '16.833575'),
 ('VHM', '64.579083', '16.833575'),
 ('VXO', '56.929144', '14.727994'),
 ('VXO', '56.929144', '14.727994'),
 ('ADQ', '57.749967', '-152.493856'),
 ('ADQ', '57.749967', '-152.493856'),
 ('ADQ', '57.749967', '-152.493856'),
 ('ADQ', '57.749967', '-152.493856'),
 ('ADQ', '57.749967', '-152.493856'),
 ('AOS', '57.471389', '-153.815278'),
 ('KKB', '58.190833', '-152.370556'),
 ('KLN', '57.535', '-153.976667'),
 ('KOZ', '57.922876', '-152.500511'),
 ('SYB', '58.166667', '-152.5'),
 ('BSO', '20.451322', '121.979883'),
 ('BXU', '8.951322', '125.477972'),
 ('CBO', '7.165242', '124.209619'),
 ('CGY', '8.415619', '124.611219'),
 ('CRM', '12.502417', '124.635778'),
 ('DGT', '9.333714', '123.300472'),
 ('DWC', '24.55056', '55.103174'),
 ('GES', '6.106439', '125.2353'),
 ('KLO', '11.679431', '122.376294'),
 ('LGP', '13.157064', '123.746247'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('MPH', '11.9214999', '121.953'),
 ('OZC', '8.178508', '123.841731'),
 ('PPS', '9.742119', '118.758731'),
 ('RXS', '11.597669', '122.751669'),
 ('SUG', '9.757567', '125.479328'),
 ('TUG', '17.638311', '121.730614'),
 ('ZAM', '6.922419', '122.059633'),
 ('AUX', '-7.228333', '-48.240833'),
 ('BRA', '-12.083333', '-45'),
 ('BRA', '-12.083333', '-45'),
 ('BSB', '-15.8711', '-47.918625'),
 ('BSB', '-15.8711', '-47.918625'),
 ('BSB', '-15.8711', '-47.918625'),
 ('CAC', '-25.000339', '-53.500764'),
 ('CGB', '-15.652931', '-56.116719'),
 ('CGB', '-15.652931', '-56.116719'),
 ('CGR', '-20.468667', '-54.6725'),
 ('DOU', '-22.220833', '-54.805833'),
 ('DOU', '-22.220833', '-54.805833'),
 ('GIG', '-22.808903', '-43.243647'),
 ('GRU', '-23.432075', '-46.469511'),
 ('GRU', '-23.432075', '-46.469511'),
 ('GRU', '-23.432075', '-46.469511'),
 ('GRU', '-23.432075', '-46.469511'),
 ('GRU', '-23.432075', '-46.469511'),
 ('GRU', '-23.432075', '-46.469511'),
 ('GYN', '-16.632033', '-49.220686'),
 ('GYN', '-16.632033', '-49.220686'),
 ('GYN', '-16.632033', '-49.220686'),
 ('GYN', '-16.632033', '-49.220686'),
 ('OPS', '-11.885', '-55.586'),
 ('OPS', '-11.885', '-55.586'),
 ('PLU', '-19.851181', '-43.950628'),
 ('PMW', '-10.241667', '-48.35278'),
 ('PMW', '-10.241667', '-48.35278'),
 ('RAO', '-21.134167', '-47.774189'),
 ('RAO', '-21.134167', '-47.774189'),
 ('RAO', '-21.134167', '-47.774189'),
 ('RAO', '-21.134167', '-47.774189'),
 ('RAO', '-21.134167', '-47.774189'),
 ('RAO', '-21.134167', '-47.774189'),
 ('RAO', '-21.134167', '-47.774189'),
 ('SJP', '-20.816567', '-49.406511'),
 ('SSA', '-12.910994', '-38.331044'),
 ('SSA', '-12.910994', '-38.331044'),
 ('UBA', '-19.765', '-47.964778'),
 ('UBA', '-19.765', '-47.964778'),
 ('UDI', '-18.882844', '-48.225594'),
 ('UDI', '-18.882844', '-48.225594'),
 ('UDI', '-18.882844', '-48.225594'),
 ('UDI', '-18.882844', '-48.225594'),
 ('VDC', '-14.862761', '-40.863106'),
 ('VDC', '-14.862761', '-40.863106'),
 ('BRL', '40.7832', '-91.1255'),
 ('BRL', '40.7832', '-91.1255'),
 ('DEC', '39.834564', '-88.865689'),
 ('DEC', '39.834564', '-88.865689'),
 ('JBR', '35.831708', '-90.646417'),
 ('ORD', '41.978603', '-87.904842'),
 ('ORD', '41.978603', '-87.904842'),
 ('STL', '38.748697', '-90.370028'),
 ('STL', '38.748697', '-90.370028'),
 ('STL', '38.748697', '-90.370028'),
 ('CGA', '55.478889', '-133.147778'),
 ('CGA', '55.478889', '-133.147778'),
 ('HYL', '55.481667', '-132.646111'),
 ('HYL', '55.481667', '-132.646111'),
 ('HYL', '55.481667', '-132.646111'),
 ('KTB', '55.688056', '-132.536667'),
 ('KTB', '55.688056', '-132.536667'),
 ('KTN', '55.355556', '-131.71375'),
 ('KTN', '55.355556', '-131.71375'),
 ('KTN', '55.355556', '-131.71375'),
 ('KTN', '55.355556', '-131.71375'),
 ('MTM', '55.131111', '-131.578056'),
 ('ACC', '5.605186', '-0.166786'),
 ('ACC', '5.605186', '-0.166786'),
 ('ACC', '5.605186', '-0.166786'),
 ('BCN', '41.297078', '2.078464'),
 ('BJL', '13.337961', '-16.652206'),
 ('BJL', '13.337961', '-16.652206'),
 ('BJL', '13.337961', '-16.652206'),
 ('CKY', '9.576889', '-13.611961'),
 ('DKR', '14.739708', '-17.490225'),
 ('DKR', '14.739708', '-17.490225'),
 ('DKR', '14.739708', '-17.490225'),
 ('DKR', '14.739708', '-17.490225'),
 ('DKR', '14.739708', '-17.490225'),
 ('DKR', '14.739708', '-17.490225'),
 ('DLA', '4.006081', '9.719481'),
 ('DLA', '4.006081', '9.719481'),
 ('FNA', '8.616444', '-13.195489'),
 ('FNA', '8.616444', '-13.195489'),
 ('FNA', '8.616444', '-13.195489'),
 ('FNA', '8.616444', '-13.195489'),
 ('LGW', '51.148056', '-0.190278'),
 ('LOS', '6.577369', '3.321156'),
 ('LOS', '6.577369', '3.321156'),
 ('LOS', '6.577369', '3.321156'),
 ('LOS', '6.577369', '3.321156'),
 ('OXB', '11.89485', '-15.653681'),
 ('OXB', '11.89485', '-15.653681'),
 ('ROB', '6.233789', '-10.362311'),
 ('ROB', '6.233789', '-10.362311'),
 ('ROB', '6.233789', '-10.362311'),
 ('AKV', '60.8186', '-78.1486'),
 ('AKV', '60.8186', '-78.1486'),
 ('XGR', '58.7114', '-65.9928'),
 ('YGL', '53.625278', '-77.704167'),
 ('YGL', '53.625278', '-77.704167'),
 ('YGL', '53.625278', '-77.704167'),
 ('YGW', '55.2819', '-77.7653'),
 ('YGW', '55.2819', '-77.7653'),
 ('YGW', '55.2819', '-77.7653'),
 ('YGW', '55.2819', '-77.7653'),
 ('YGW', '55.2819', '-77.7653'),
 ('YGW', '55.2819', '-77.7653'),
 ('YIK', '62.4173', '-77.9253'),
 ('YIK', '62.4173', '-77.9253'),
 ('YKG', '60.0272', '-69.9992'),
 ('YKG', '60.0272', '-69.9992'),
 ('YKG', '60.0272', '-69.9992'),
 ('YKL', '54.805278', '-66.805278'),
 ('YKL', '54.805278', '-66.805278'),
 ('YKL', '54.805278', '-66.805278'),
 ('YKL', '54.805278', '-66.805278'),
 ('YPH', '58.4719', '-78.0769'),
 ('YPH', '58.4719', '-78.0769'),
 ('YPH', '58.4719', '-78.0769'),
 ('YPJ', '59.2967', '-69.5997'),
 ('YPJ', '59.2967', '-69.5997'),
 ('YPJ', '59.2967', '-69.5997'),
 ('YPX', '60.0506', '-77.2869'),
 ('YPX', '60.0506', '-77.2869'),
 ('YPX', '60.0506', '-77.2869'),
 ('YPX', '60.0506', '-77.2869'),
 ('YQB', '46.791111', '-71.393333'),
 ('YQB', '46.791111', '-71.393333'),
 ('YQC', '61.0464', '-69.6178'),
 ('YQC', '61.0464', '-69.6178'),
 ('YSK', '56.5378', '-79.2467'),
 ('YSK', '56.5378', '-79.2467'),
 ('YTQ', '58.6678', '-69.9558'),
 ('YTQ', '58.6678', '-69.9558'),
 ('YUD', '56.5361', '-76.5183'),
 ('YUD', '56.5361', '-76.5183'),
 ('YUD', '56.5361', '-76.5183'),
 ('YUL', '45.470556', '-73.740833'),
 ('YUL', '45.470556', '-73.740833'),
 ('YUL', '45.470556', '-73.740833'),
 ('YUL', '45.470556', '-73.740833'),
 ('YUY', '48.206111', '-78.835556'),
 ('YUY', '48.206111', '-78.835556'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YVP', '58.096111', '-68.426944'),
 ('YWB', '61.588611', '-71.929444'),
 ('YWB', '61.588611', '-71.929444'),
 ('YWK', '52.921944', '-66.864444'),
 ('YWK', '52.921944', '-66.864444'),
 ('YZG', '62.1794', '-75.6672'),
 ('YZG', '62.1794', '-75.6672'),
 ('YZV', '50.223333', '-66.265556'),
 ('YZV', '50.223333', '-66.265556'),
 ('JIB', '11.5472', '43.1594'),
 ('JIB', '11.5472', '43.1594'),
 ('JIB', '11.5472', '43.1594'),
 ('MGQ', '2.01444', '45.3047'),
 ('NBO', '-1.319167', '36.9275'),
 ('BKK', '13.681108', '100.747283'),
 ('DRW', '-12.4083333', '130.87266'),
 ('HAK', '19.934856', '110.458961'),
 ('HGH', '30.229503', '120.434453'),
 ('HKG', '22.308919', '113.914603'),
 ('HKT', '8.1132', '98.316872'),
 ('KIX', '34.4347222', '135.244167'),
 ('KIX', '34.4347222', '135.244167'),
 ('KUL', '2.745578', '101.709917'),
 ('MNL', '14.508647', '121.019581'),
 ('MNL', '14.508647', '121.019581'),
 ('PEN', '5.297139', '100.276864'),
 ('PER', '-31.940278', '115.966944'),
 ('PNH', '11.546556', '104.844139'),
 ('REP', '13.410666', '103.81284'),
 ('RGN', '16.907305', '96.133222'),
 ('SGN', '10.818797', '106.651856'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SIN', '1.350189', '103.994433'),
 ('SWA', '23.4', '116.683'),
 ('TPE', '25.077731', '121.232822'),
 ('TPE', '25.077731', '121.232822'),
 ('ACH', '47.485033', '9.560775'),
 ('DRS', '51.132767', '13.767161'),
 ('DUS', '51.289453', '6.766775'),
 ('EBA', '42.760277', '10.239445'),
 ('EBA', '42.760277', '10.239445'),
 ('EBA', '42.760277', '10.239445'),
 ('EBA', '42.760277', '10.239445'),
 ('FDH', '47.671317', '9.511486'),
 ('FDH', '47.671317', '9.511486'),
 ('FDH', '47.671317', '9.511486'),
 ('FDH', '47.671317', '9.511486'),
 ('FDH', '47.671317', '9.511486'),
 ('FDH', '47.671317', '9.511486'),
 ('FMM', '47.988758', '10.2395'),
 ('GRZ', '46.991067', '15.439628'),
 ('HAM', '53.630389', '9.988228'),
 ('MUC', '48.353783', '11.786086'),
 ('NAP', '40.886033', '14.290781'),
 ('OLB', '40.898661', '9.517628'),
 ('SZG', '47.793304', '13.004333'),
 ('TXL', '52.559686', '13.287711'),
 ('ZAD', '44.108269', '15.346697'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ZRH', '47.464722', '8.549167'),
 ('ATL', '33.636719', '-84.428067'),
 ('ATL', '33.636719', '-84.428067'),
 ('ATL', '33.636719', '-84.428067'),
 ('ATL', '33.636719', '-84.428067'),
 ('ATL', '33.636719', '-84.428067'),
 ('ATL', '33.636719', '-84.428067'),
 ('BIM', '25.699881', '-79.264656'),
 ('ELH', '25.474861', '-76.683489'),
 ('ELH', '25.474861', '-76.683489'),
 ('EYW', '24.556111', '-81.759556'),
 ('EYW', '24.556111', '-81.759556'),
 ('EYW', '24.556111', '-81.759556'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FLL', '26.072583', '-80.15275'),
 ('FPO', '26.558686', '-78.695553'),
 ('GGT', '23.562631', '-75.877958'),
 ('GGT', '23.562631', '-75.877958'),
 ('GHB', '25.284706', '-76.331011'),
 ('GLH', '33.4829', '-90.9856'),
 ('GNV', '29.690056', '-82.271778'),
 ('GNV', '29.690056', '-82.271778'),
 ('JAX', '30.494056', '-81.687861'),
 ('JAX', '30.494056', '-81.687861'),
 ('LWB', '37.858333', '-80.399444'),
 ('MCN', '32.69285', '-83.649211'),
 ('MCN', '32.69285', '-83.649211'),
 ('MCO', '28.429394', '-81.308994'),
 ('MCO', '28.429394', '-81.308994'),
 ('MCO', '28.429394', '-81.308994'),
 ('MCO', '28.429394', '-81.308994'),
 ('MCO', '28.429394', '-81.308994'),
 ('MCO', '28.429394', '-81.308994'),
 ('MCO', '28.429394', '-81.308994'),
 ('MEI', '32.332624', '-88.751868'),
 ('MHH', '26.511406', '-77.083472'),
 ('MHH', '26.511406', '-77.083472'),
 ('MHH', '26.511406', '-77.083472'),
 ('MHH', '26.511406', '-77.083472'),
 ('MSL', '34.7453', '-87.6102'),
 ('PBI', '26.683161', '-80.095589'),
 ('PBI', '26.683161', '-80.095589'),
 ('PBI', '26.683161', '-80.095589'),
 ('PIB', '31.4671', '-89.3371'),
 ('PNS', '30.473425', '-87.186611'),
 ('PNS', '30.473425', '-87.186611'),
 ('RSW', '26.536167', '-81.755167'),
 ('RSW', '26.536167', '-81.755167'),
 ('TCB', '26.745336', '-77.391269'),
 ('TLH', '30.396528', '-84.350333'),
 ('TLH', '30.396528', '-84.350333'),
 ('TPA', '27.975472', '-82.53325'),
 ('TPA', '27.975472', '-82.53325'),
 ('TPA', '27.975472', '-82.53325'),
 ('TPA', '27.975472', '-82.53325'),
 ('TPA', '27.975472', '-82.53325'),
 ('TPA', '27.975472', '-82.53325'),
 ('TPA', '27.975472', '-82.53325'),
 ('TUP', '34.2681', '-88.7699'),
 ('TUP', '34.2681', '-88.7699'),
 ('AMS', '52.308613', '4.763889'),
 ('AMS', '52.308613', '4.763889'),
 ('BCN', '41.297078', '2.078464'),
 ('BCN', '41.297078', '2.078464'),
 ('BCN', '41.297078', '2.078464'),
 ('BGY', '45.673889', '9.704166'),
 ('BLQ', '44.535444', '11.288667'),
 ('BRU', '50.901389', '4.484444'),
 ('BRU', '50.901389', '4.484444'),
 ('BRU', '50.901389', '4.484444'),
 ('CGN', '50.865917', '7.142744'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CMN', '33.367467', '-7.589967'),
 ('CUF', '44.547019', '7.623217'),
 ('FEZ', '33.927261', '-4.977958'),
 ('LGW', '51.148056', '-0.190278'),
 ('LGW', '51.148056', '-0.190278'),
 ('LYS', '45.726387', '5.090833'),
 ('MPL', '43.576194', '3.963014'),
 ('MPL', '43.576194', '3.963014'),
 ('MPL', '43.576194', '3.963014'),
 ('NDR', '34.9888', '-3.02821'),
 ('NDR', '34.9888', '-3.02821'),
 ('NDR', '34.9888', '-3.02821'),
 ('NDR', '34.9888', '-3.02821'),
 ('NDR', '34.9888', '-3.02821'),
 ('NDR', '34.9888', '-3.02821'),
 ('PMI', '39.55361', '2.727778'),
 ('SAW', '40.898553', '29.309219'),
 ('TLS', '43.629075', '1.363819'),
 ('TNG', '35.726917', '-5.916889'),
 ('TNG', '35.726917', '-5.916889'),
 ('TNG', '35.726917', '-5.916889'),
 ('TNG', '35.726917', '-5.916889'),
 ('TSF', '45.6484', '12.194422'),
 ('AUA', '12.501389', '-70.015221'),
 ('AUA', '12.501389', '-70.015221'),
 ('BON', '12.131044', '-68.268511'),

### Grouping statements

Combines `select` and `group by` when you want aggregates by values

`select` `min(x)` ... `max()`, `sum()`, etc

`group by x`

**Task**<br>
- Which countries have the highest amount of active airports?
- Which countries have the highest amount of inactive airports?
- What about airports by timezones?

In [65]:
cursor.execute('''select country, count(country) as cc from airlines where active = 'Y' 
                  group by country order by cc desc;''').fetchall()

[('United States', 141),
 ('Russia', 72),
 ('United Kingdom', 40),
 ('Germany', 37),
 ('Canada', 34),
 ('Australia', 26),
 ('China', 25),
 ('Spain', 24),
 ('Brazil', 23),
 ('France', 22),
 ('Japan', 19),
 ('Italy', 18),
 ('India', 17),
 ('Indonesia', 17),
 ('Thailand', 16),
 ('Turkey', 16),
 ('Sweden', 15),
 ('Switzerland', 14),
 ('Portugal', 13),
 ('Ukraine', 13),
 ('Austria', 12),
 ('Egypt', 12),
 ('Finland', 12),
 ('Mexico', 12),
 ('Peru', 11),
 ('Argentina', 10),
 ('Greece', 10),
 ('South Africa', 10),
 ('Colombia', 9),
 ('Iceland', 9),
 ('Netherlands', 9),
 ('Philippines', 8),
 ('Poland', 8),
 ('Romania', 8),
 ('Singapore', 8),
 ('United Arab Emirates', 8),
 ('Denmark', 7),
 ('Ecuador', 7),
 ('Iran', 7),
 ('Ireland', 7),
 ('Malaysia', 7),
 ('Pakistan', 7),
 ('Taiwan', 7),
 ('Vietnam', 7),
 ('Belgium', 6),
 ('Burma', 6),
 ('Chile', 6),
 ('Georgia', 6),
 ('Israel', 6),
 ('Kazakhstan', 6),
 ('Nepal', 6),
 ('Norway', 6),
 ('South Korea', 6),
 ('Cambodia', 5),
 ('Czech Republic', 5),
 ('Dominican Republic', 5),
 ('Lithuania', 5),
 ('Morocco', 5),
 ('Nigeria', 5),
 ('Republic of Korea', 5),
 ('Slovakia', 5),
 ('Afghanistan', 4),
 ('Azerbaijan', 4),
 ('Congo (Kinshasa)', 4),
 ('Kyrgyzstan', 4),
 ('Latvia', 4),
 ('Maldives', 4),
 ('New Zealand', 4),
 ('Tanzania', 4),
 ('Tunisia', 4),
 ('Uruguay', 4),
 ('Venezuela', 4),
 ('Bangladesh', 3),
 ('Bulgaria', 3),
 ('Cameroon', 3),
 ('Cyprus', 3),
 ('Estonia', 3),
 ('Guinea', 3),
 ('Haiti', 3),
 ('Hong Kong SAR of China', 3),
 ('Hungary', 3),
 ('Kenya', 3),
 ('Kuwait', 3),
 ('Lebanon', 3),
 ('Libya', 3),
 ('Mauritania', 3),
 ('Mongolia', 3),
 ('Myanmar', 3),
 ('Netherlands Antilles', 3),
 ('Saudi Arabia', 3),
 ('Serbia', 3),
 ('Sierra Leone', 3),
 ('Uganda', 3),
 ('Zambia', 3),
 ('Zimbabwe', 3),
 ('Albania', 2),
 ('Algeria', 2),
 ('Angola', 2),
 ('Armenia', 2),
 ('Bahamas', 2),
 ('Barbados', 2),
 ('Belarus', 2),
 ('Belize', 2),
 ('Bolivia', 2),
 ('Bosnia and Herzegovina', 2),
 ('Costa Rica', 2),
 ('Croatia', 2),
 ('Cuba', 2),
 ('Djibouti', 2),
 ('Eritrea', 2),
 ('Fiji', 2),
 ('Ghana', 2),
 ('Hong Kong', 2),
 ('Iraq', 2),
 ('Ivory Coast', 2),
 ('Jordan', 2),
 ('Macao', 2),
 ('Macedonia', 2),
 ('Malawi', 2),
 ('Malta', 2),
 ('Mauritius', 2),
 ('Moldova', 2),
 ('Mozambique', 2),
 ('Oman', 2),
 ('Papua New Guinea', 2),
 ('Paraguay', 2),
 ('Qatar', 2),
 ('Russian Federation', 2),
 ('Sri Lanka', 2),
 ('Sudan', 2),
 ('Tajikistan', 2),
 ('Uzbekistan', 2),
 ('Yemen', 2),
 ('\\N', 2),
 (' S.A.', 1),
 ('ALASKA', 1),
 ('AVIANCA', 1),
 ('American Samoa', 1),
 ('Antigua and Barbuda', 1),
 ('Aruba', 1),
 ('Bahrain', 1),
 ('Benin', 1),
 ('Bhutan', 1),
 ('Botswana', 1),
 ('British Virgin Islands', 1),
 ('Brunei', 1),
 ('Burkina Faso', 1),
 ('Burundi', 1),
 ('Canadian Territories', 1),
 ('Cape Verde', 1),
 ('Cayman Islands', 1),
 ('Comoros', 1),
 ('Cook Islands', 1),
 ('DRAGON', 1),
 ("Democratic People's Republic of Korea", 1),
 ('Equatorial Guinea', 1),
 ('Ethiopia', 1),
 ('Faroe Islands', 1),
 ('French Guiana', 1),
 ('French Polynesia', 1),
 ('Gabon', 1),
 ('Guadeloupe', 1),
 ('Guatemala', 1),
 ('Honduras', 1),
 ('Jamaica', 1),
 ('Kiribati', 1),
 ('Lao Peoples Democratic Republic', 1),
 ('Luxembourg', 1),
 ('Madagascar', 1),
 ('Marshall Islands', 1),
 ('Montenegro', 1),
 ('Namibia', 1),
 ('Nauru', 1),
 ('Niger', 1),
 ('Palau', 1),
 ('Panama', 1),
 ('Puerto Rico', 1),
 ('Republic of the Congo', 1),
 ('Reunion', 1),
 ('Rwanda', 1),
 ('Saint Vincent and the Grenadines', 1),
 ('Samoa', 1),
 ('Sao Tome and Principe', 1),
 ('Senegal', 1),
 ('Seychelles', 1),
 ('Slovenia', 1),
 ('Solomon Islands', 1),
 ('Suriname', 1),
 ('Syria', 1),
 ('Syrian Arab Republic', 1),
 ('Togo', 1),
 ('Trinidad and Tobago', 1),
 ('Turkmenistan', 1),
 ('Vanuatu', 1),
 (None, 0)]

In [66]:
cursor.execute('''select country, count(country) as cc from airlines where active = 'N' 
                  group by country order by cc desc;''').fetchall()

[('United States', 939),
 ('Mexico', 427),
 ('United Kingdom', 367),
 ('Canada', 284),
 ('Russia', 158),
 ('Spain', 142),
 ('France', 97),
 ('Germany', 94),
 ('South Africa', 81),
 ('Nigeria', 80),
 ('Ukraine', 76),
 ('Kazakhstan', 73),
 ('Italy', 72),
 ('Australia', 67),
 ('Sweden', 55),
 ('Sudan', 47),
 ('Switzerland', 46),
 ('China', 45),
 ('Netherlands', 43),
 ('Austria', 38),
 ('Egypt', 36),
 ('Angola', 35),
 ('Brazil', 35),
 ('Chile', 35),
 ('Colombia', 34),
 ('Mauritania', 32),
 ('Portugal', 32),
 ('Thailand', 32),
 ('Indonesia', 31),
 ('Kyrgyzstan', 29),
 ('Czech Republic', 27),
 ('Bulgaria', 25),
 ('Denmark', 25),
 ('Dominican Republic', 25),
 ('Japan', 25),
 ('Iran', 24),
 ('New Zealand', 24),
 ('Libya', 23),
 ('Norway', 23),
 ('Sierra Leone', 23),
 ('Turkey', 23),
 ('United Arab Emirates', 23),
 ('Pakistan', 22),
 ('Venezuela', 22),
 ('Belgium', 21),
 ('Ireland', 21),
 ('Uganda', 21),
 ('Kenya', 20),
 ('Zambia', 20),
 ('Democratic Republic of the Congo', 19),
 ('Ecuador', 19),
 ('Greece', 19),
 ('Ghana', 17),
 ('Moldova', 17),
 ('Israel', 16),
 ('Armenia', 15),
 ('Hungary', 15),
 ('Ivory Coast', 15),
 ('Peru', 15),
 ('Argentina', 14),
 ('Haiti', 14),
 ('Slovakia', 14),
 ('Lebanon', 13),
 ('Lithuania', 13),
 ('Philippines', 13),
 ('Cambodia', 12),
 ('Georgia', 12),
 ('Poland', 12),
 ('Senegal', 12),
 ('Guinea', 11),
 ('Iceland', 11),
 ('Luxembourg', 11),
 ('Bangladesh', 10),
 ('Equatorial Guinea', 10),
 ('Gabon', 10),
 ('Namibia', 10),
 ('Serbia', 10),
 ('Democratic Republic of Congo', 9),
 ('India', 9),
 ('Latvia', 9),
 ('Mali', 9),
 ('Romania', 9),
 ('Uruguay', 9),
 ('Uzbekistan', 9),
 ('Bahrain', 8),
 ('Barbados', 8),
 ('Chad', 8),
 ('Croatia', 8),
 ('Guinea-Bissau', 8),
 ('Belarus', 7),
 ('Finland', 7),
 ('Malaysia', 7),
 ('Bahamas', 6),
 ('Bolivia', 6),
 ('Burkina Faso', 6),
 ('Costa Rica', 6),
 ('Djibouti', 6),
 ('Gambia', 6),
 ('Sao Tome and Principe', 6),
 ('Swaziland', 6),
 ('Tanzania', 6),
 ('Benin', 5),
 ('Central African Republic', 5),
 ('Cyprus', 5),
 ('El Salvador', 5),
 ('Estonia', 5),
 ('Guatemala', 5),
 ('Honduras', 5),
 ('Jordan', 5),
 ('Mongolia', 5),
 ('Mozambique', 5),
 ('Nepal', 5),
 ('Netherland', 5),
 ('Panama', 5),
 ('Rwanda', 5),
 ('S', 5),
 ('Slovenia', 5),
 ('Somali Republic', 5),
 ('Suriname', 5),
 ('Tajikistan', 5),
 ('Afghanistan', 4),
 ('Algeria', 4),
 ('Aruba', 4),
 ('Cameroon', 4),
 ('Ethiopia', 4),
 ('Guyana', 4),
 ('Macedonia', 4),
 ('Malta', 4),
 ('Netherlands Antilles', 4),
 ('Nicaragua', 4),
 ('Oman', 4),
 ('Republic of the Congo', 4),
 ('Sri Lanka', 4),
 ('Syrian Arab Republic', 4),
 ('Tunisia', 4),
 ('Turks and Caicos Islands', 4),
 ('Zimbabwe', 4),
 ('Antigua and Barbuda', 3),
 ('Azerbaijan', 3),
 ('Cuba', 3),
 ('Fiji', 3),
 ('Liberia', 3),
 ('Malawi', 3),
 ('Maldives', 3),
 ('Morocco', 3),
 ('Niger', 3),
 ('Papua New Guinea', 3),
 ('Republic of Korea', 3),
 ('Saudi Arabia', 3),
 ('Singapore', 3),
 ('Togo', 3),
 ('Albania', 2),
 ('Bosnia and Herzegovina', 2),
 ('Burundi', 2),
 ('Cape Verde', 2),
 ('Comoros', 2),
 ('Hong Kong SAR of China', 2),
 ('Lao Peoples Democratic Republic', 2),
 ('Madagascar', 2),
 ('Palau', 2),
 ('Qatar', 2),
 ('Saint Lucia', 2),
 ('Solomon Islands', 2),
 ('Tonga', 2),
 ('Turkmenistan', 2),
 (' Boonville Stage Line', 1),
 ('ACOM', 1),
 ('ACTIVE AERO', 1),
 ('AEROCENTER', 1),
 ('AEROCESAR', 1),
 ('AEROPERLAS', 1),
 ('AEROPUMA', 1),
 ('AEROSOL', 1),
 ('AEROSUN', 1),
 ('AEROVARADERO', 1),
 ('AEROWEE', 1),
 ('AIR CLASS', 1),
 ('AIR FREIGHTER', 1),
 ('AIR PRINT', 1),
 ('AIR-MAUR', 1),
 ('AIREX', 1),
 ('AIRFLIGHT', 1),
 ('AIRMAN', 1),
 ('AIRNAT', 1),
 ('AIRPAC', 1),
 ('AIRPORT HELICOPTER', 1),
 ('AIRWAVE', 1),
 ('ALAMO', 1),
 ('ALASKA PACIFIC', 1),
 ('ALCON', 1),
 ('ALDAWLYH AIR', 1),
 ('ALL STAR', 1),
 ('ALNACIONAL', 1),
 ('ANTARES', 1),
 ('APPALACHIAN', 1),
 ('AQUILINE', 1),
 ('ARIZAIR', 1),
 ('ARMSTRONG', 1),
 ('ASA PESADA', 1),
 ('ASTORIA', 1),
 ('ASUR', 1),
 ('ATCO', 1),
 ('ATLANTIC NICARAGUA', 1),
 ('ATLANTIS CANADA', 1),
 ('AUDI AIR', 1),
 ('AURORA AIR', 1),
 ('AUSA', 1),
 ('AVEMEX', 1),
 ('AVINOR', 1),
 ('AVIOQUINTANA', 1),
 ('AZIMUT', 1),
 ('Air S', 1),
 ('Belize', 1),
 ('Bermuda', 1),
 ('COMPANY AS', 1),
 ('Cayman Islands', 1),
 ('Congo (Brazzaville)', 1),
 ('Cook Islands', 1),
 ("Cote d'Ivoire", 1),
 ('Faroe Islands', 1),
 ('Hong Kong', 1),
 ('Jamaica', 1),
 ('Kiribati', 1),
 ('Kuwait', 1),
 ('LAP', 1),
 ('Macao', 1),
 ('Mauritius', 1),
 ('Monaco', 1),
 ('Montenegro', 1),
 ('Montserrat', 1),
 ('Nauru', 1),
 ('ODINN', 1),
 ('Paraguay', 1),
 ('RENTAXEL', 1),
 ('Russia]]', 1),
 ('Russian Federation', 1),
 ('SCHEFF', 1),
 ('SWISSBIRD', 1),
 ('Saint Kitts and Nevis', 1),
 ('Saint Vincent and the Grenadines', 1),
 ('Taiwan', 1),
 ('Trinidad and Tobago', 1),
 ('UNIFORM OSCAR', 1),
 ('UNited Kingdom', 1),
 ('VELES', 1),
 ('Vietnam', 1),
 ('WATCHDOG', 1),
 ('Yemen', 1),
 ('\\N', 1),
 (None, 0)]

In [71]:
cursor.execute('''select country, timezone, count(code) as cc from airports 
                  group by timezone order by country;''').fetchall()

[('Afghanistan', 'Asia/Kabul', 16),
 ('Albania', 'Europe/Tirane', 1),
 ('Algeria', 'Africa/Algiers', 35),
 ('American Samoa', 'Pacific/Pago_Pago', 3),
 ('Angola', 'Africa/Luanda', 22),
 ('Anguilla', 'America/Anguilla', 1),
 ('Antarctica', 'Antarctica/South_Pole', 0),
 ('Antigua and Barbuda', 'America/Antigua', 2),
 ('Argentina', 'America/Cordoba', 72),
 ('Armenia', 'Asia/Yerevan', 2),
 ('Aruba', 'America/Aruba', 1),
 ('Australia', 'Australia/Adelaide', 15),
 ('Australia', 'Australia/Brisbane', 70),
 ('Australia', 'Australia/Darwin', 21),
 ('Australia', 'Australia/Hobart', 12),
 ('Australia', 'Australia/Melbourne', 7),
 ('Australia', 'Australia/Perth', 36),
 ('Australia', 'Australia/Sydney', 45),
 ('Austria', 'Europe/Vienna', 9),
 ('Azerbaijan', 'Asia/Baku', 7),
 ('Bahamas', 'America/Nassau', 25),
 ('Bahrain', 'Asia/Bahrain', 1),
 ('Bangladesh', 'Asia/Dhaka', 9),
 ('Barbados', 'America/Barbados', 1),
 ('Belarus', 'Europe/Minsk', 6),
 ('Belgium', 'Europe/Brussels', 10),
 ('Belize', 'America/Belize', 12),
 ('Benin', 'Africa/Porto-Novo', 1),
 ('Bermuda', 'Atlantic/Bermuda', 1),
 ('Bhutan', 'Asia/Thimphu', 1),
 ('Bolivia', 'America/La_Paz', 19),
 ('Bosnia and Herzegovina', 'Europe/Sarajevo', 3),
 ('Botswana', 'Africa/Gaborone', 11),
 ('Brazil', 'America/Boa_Vista', 39),
 ('Brazil', 'America/Campo_Grande', 14),
 ('Brazil', 'America/Fortaleza', 34),
 ('Brazil', 'America/Rio_Branco', 2),
 ('Brazil', 'America/Sao_Paulo', 80),
 ('British Indian Ocean Territory', 'Indian/Chagos', 0),
 ('British Virgin Islands', 'America/Tortola', 2),
 ('Brunei', 'Asia/Brunei', 1),
 ('Bulgaria', 'Europe/Sofia', 6),
 ('Burkina Faso', 'Africa/Ouagadougou', 2),
 ('Burma', 'Asia/Rangoon', 28),
 ('Burundi', 'Africa/Bujumbura', 1),
 ('Cambodia', 'Asia/Phnom_Penh', 6),
 ('Cameroon', 'Africa/Douala', 10),
 ('Canada', 'America/Blanc-Sablon', 6),
 ('Canada', 'America/Coral_Harbour', 3),
 ('Canada', 'America/Dawson_Creek', 2),
 ('Canada', 'America/Edmonton', 55),
 ('Canada', 'America/Halifax', 23),
 ('Canada', 'America/Regina', 18),
 ('Canada', 'America/St_Johns', 9),
 ('Canada', 'America/Toronto', 133),
 ('Canada', 'America/Vancouver', 61),
 ('Canada', 'America/Winnipeg', 59),
 ('Cape Verde', 'Atlantic/Cape_Verde', 7),
 ('Cayman Islands', 'America/Cayman', 3),
 ('Central African Republic', 'Africa/Bangui', 3),
 ('Chad', 'Africa/Ndjamena', 6),
 ('Chile', 'America/Santiago', 23),
 ('Chile', 'Pacific/Easter', 1),
 ('China', 'Asia/Chongqing', 187),
 ('Christmas Island', 'Indian/Christmas', 1),
 ('Cocos (Keeling) Islands', 'Indian/Cocos', 1),
 ('Colombia', 'America/Bogota', 63),
 ('Comoros', 'Indian/Comoro', 4),
 ('Congo (Brazzaville)', 'Africa/Brazzaville', 5),
 ('Congo (Kinshasa)', 'Africa/Kigali', 4),
 ('Congo (Kinshasa)', 'Africa/Kinshasa', 16),
 ('Congo (Kinshasa)', 'Africa/Lubumbashi', 14),
 ('Cook Islands', 'Pacific/Rarotonga', 8),
 ('Costa Rica', 'America/Costa_Rica', 20),
 ("Cote d'Ivoire", 'Africa/Abidjan', 7),
 ('Croatia', 'Europe/Zagreb', 8),
 ('Cuba', 'America/Havana', 19),
 ('Cuba', '\\N', 42),
 ('Cyprus', 'Asia/Nicosia', 4),
 ('Czech Republic', 'Europe/Prague', 9),
 ('Denmark', 'Europe/Copenhagen', 16),
 ('Djibouti', 'Africa/Djibouti', 3),
 ('Dominica', 'America/Dominica', 2),
 ('Dominican Republic', 'America/Santo_Domingo', 11),
 ('East Timor', 'Asia/Dili', 1),
 ('Ecuador', 'America/Guayaquil', 18),
 ('Ecuador', 'Pacific/Galapagos', 2),
 ('Egypt', 'Africa/Cairo', 20),
 ('El Salvador', 'America/El_Salvador', 1),
 ('Equatorial Guinea', 'Africa/Malabo', 2),
 ('Eritrea', 'Africa/Asmera', 4),
 ('Estonia', 'Europe/Tallinn', 5),
 ('Ethiopia', 'Africa/Addis_Ababa', 29),
 ('Falkland Islands', 'Atlantic/Stanley', 2),
 ('Faroe Islands', 'Atlantic/Faeroe', 1),
 ('Fiji', 'Pacific/Fiji', 16),
 ('Finland', 'Europe/Helsinki', 29),
 ('Finland', 'Europe/Mariehamn', 1),
 ('France', 'Europe/Paris', 131),
 ('French Guiana', 'America/Cayenne', 4),
 ('French Polynesia', 'Pacific/Gambier', 1),
 ('French Polynesia', 'Pacific/Marquesas', 4),
 ('French Polynesia', 'Pacific/Tahiti', 24),
 ('Gabon', 'Africa/Libreville', 14),
 ('Gambia', 'Africa/Banjul', 1),
 ('Georgia', 'Asia/Tbilisi', 4),
 ('Germany', 'Europe/Berlin', 126),
 ('Ghana', 'Africa/Accra', 5),
 ('Gibraltar', 'Europe/Gibraltar', 1),
 ('Greece', 'Europe/Athens', 44),
 ('Greenland', 'America/Danmarkshavn', 0),
 ('Greenland', 'America/Godthab', 21),
 ('Greenland', 'America/Scoresbysund', 2),
 ('Greenland', 'America/Thule', 2),
 ('Grenada', 'America/Grenada', 2),
 ('Guadeloupe', 'America/Guadeloupe', 6),
 ('Guam', 'Pacific/Guam', 2),
 ('Guatemala', 'America/Guatemala', 6),
 ('Guernsey', 'Europe/Guernsey', 2),
 ('Guinea', 'Africa/Conakry', 6),
 ('Guinea-Bissau', 'Africa/Bissau', 1),
 ('Guyana', 'America/Guyana', 11),
 ('Haiti', 'America/Port-au-Prince', 4),
 ('Honduras', 'America/Tegucigalpa', 10),
 ('Hong Kong', 'Asia/Hong_Kong', 1),
 ('Hungary', 'Europe/Budapest', 6),
 ('Iceland', 'Atlantic/Reykjavik', 18),
 ('India', 'Asia/Calcutta', 101),
 ('Indonesia', 'Asia/Jakarta', 38),
 ('Indonesia', 'Asia/Jayapura', 18),
 ('Indonesia', 'Asia/Makassar', 36),
 ('Iran', 'Asia/Tehran', 42),
 ('Iraq', 'Asia/Baghdad', 7),
 ('Ireland', 'Europe/Dublin', 15),
 ('Isle of Man', 'Europe/Isle_of_Man', 1),
 ('Israel', 'Asia/Jerusalem', 7),
 ('Italy', 'Europe/Rome', 59),
 ('Jamaica', 'America/Jamaica', 6),
 ('Japan', 'Asia/Tokyo', 89),
 ('Jersey', 'Europe/Jersey', 1),
 ('Johnston Atoll', 'Pacific/Johnston', 1),
 ('Jordan', 'Asia/Amman', 4),
 ('Kazakhstan', 'Asia/Oral', 4),
 ('Kazakhstan', 'Asia/Qyzylorda', 16),
 ('Kenya', 'Africa/Nairobi', 26),
 ('Kiribati', 'Pacific/Enderbury', 1),
 ('Kiribati', 'Pacific/Tarawa', 8),
 ('Korea', 'Asia/Pyongyang', 5),
 ('Kuwait', 'Asia/Kuwait', 1),
 ('Kyrgyzstan', 'Asia/Bishkek', 3),
 ('Laos', 'Asia/Vientiane', 9),
 ('Latvia', 'Europe/Riga', 3),
 ('Lebanon', 'Asia/Beirut', 1),
 ('Lesotho', 'Africa/Maseru', 1),
 ('Liberia', 'Africa/Monrovia', 3),
 ('Libya', 'Africa/Tripoli', 12),
 ('Lithuania', 'Europe/Vilnius', 6),
 ('Luxembourg', 'Europe/Luxembourg', 1),
 ('Macau', 'Asia/Macau', 2),
 ('Macedonia', 'Europe/Skopje', 2),
 ('Madagascar', 'Indian/Antananarivo', 44),
 ('Malawi', 'Africa/Blantyre', 6),
 ('Malaysia', 'Asia/Kuala_Lumpur', 40),
 ('Maldives', 'Indian/Maldives', 10),
 ('Mali', 'Africa/Bamako', 5),
 ('Malta', 'Europe/Malta', 3),
 ('Marshall Islands', 'Pacific/Majuro', 29),
 ('Martinique', 'America/Martinique', 1),
 ('Mauritania', 'Africa/Nouakchott', 10),
 ('Mauritius', 'Indian/Mauritius', 2),
 ('Mayotte', 'Indian/Mayotte', 1),
 ('Mexico', 'America/Hermosillo', 5),
 ('Mexico', 'America/Mazatlan', 11),
 ('Mexico', 'America/Mexico_City', 55),
 ('Mexico', 'America/Tijuana', 4),
 ('Micronesia', 'Pacific/Kosrae', 1),
 ('Micronesia', 'Pacific/Ponape', 1),
 ('Micronesia', 'Pacific/Truk', 3),
 ('Midway Islands', 'Pacific/Midway', 1),
 ('Moldova', 'Europe/Chisinau', 2),
 ('Monaco', 'Europe/Monaco', 1),
 ('Mongolia', 'Asia/Hovd', 3),
 ('Mongolia', 'Asia/Ulaanbaatar', 8),
 ('Montenegro', 'Europe/Podgorica', 2),
 ('Montserrat', 'America/Montserrat', 1),
 ('Morocco', 'Africa/Casablanca', 16),
 ('Mozambique', 'Africa/Maputo', 16),
 ('Namibia', 'Africa/Windhoek', 15),
 ('Nauru', 'Pacific/Nauru', 1),
 ('Nepal', 'Asia/Katmandu', 32),
 ('Netherlands', 'Europe/Amsterdam', 17),
 ('Netherlands Antilles', 'America/Curacao', 5),
 ('New Caledonia', 'Pacific/Noumea', 11),
 ('New Zealand', 'Pacific/Auckland', 42),
 ('New Zealand', 'Pacific/Chatham', 1),
 ('Nicaragua', 'America/Managua', 8),
 ('Niger', 'Africa/Niamey', 5),
 ('Nigeria', 'Africa/Lagos', 22),
 ('Niue', 'Pacific/Niue', 1),
 ('Norfolk Island', 'Pacific/Norfolk', 1),
 ('Northern Mariana Islands', 'Pacific/Saipan', 3),
 ('Norway', 'Arctic/Longyearbyen', 2),
 ('Norway', 'Europe/Oslo', 55),
 ('Oman', 'Asia/Muscat', 6),
 ('Pakistan', 'Asia/Karachi', 36),
 ('Palau', 'Pacific/Palau', 2),
 ('Panama', 'America/Panama', 24),
 ('Papua New Guinea', 'Pacific/Port_Moresby', 56),
 ('Paraguay', 'America/Asuncion', 3),
 ('Peru', 'America/Lima', 27),
 ('Philippines', 'Asia/Manila', 48),
 ('Poland', 'Europe/Warsaw', 19),
 ('Portugal', 'Atlantic/Azores', 9),
 ('Portugal', 'Europe/Lisbon', 7),
 ('Puerto Rico', 'America/Puerto_Rico', 10),
 ('Qatar', 'Asia/Qatar', 3),
 ('Reunion', 'Indian/Reunion', 2),
 ('Romania', 'Europe/Bucharest', 21),
 ('Russia', 'Asia/Irkutsk', 6),
 ('Russia', 'Asia/Krasnoyarsk', 8),
 ('Russia', 'Asia/Magadan', 8),
 ('Russia', 'Asia/Omsk', 8),
 ('Russia', 'Asia/Vladivostok', 7),
 ('Russia', 'Asia/Yakutsk', 10),
 ('Russia', 'Asia/Yekaterinburg', 24),
 ('Russia', 'Europe/Kaliningrad', 1),
 ('Russia', 'Europe/Moscow', 72),
 ('Saint Helena', 'Atlantic/St_Helena', 1),
 ('Saint Kitts and Nevis', 'America/St_Kitts', 2),
 ('Saint Lucia', 'America/St_Lucia', 2),
 ('Saint Pierre and Miquelon', 'America/Miquelon', 2),
 ('Saint Vincent and the Grenadines', 'America/St_Vincent', 5),
 ('Samoa', 'Pacific/Apia', 4),
 ('Sao Tome and Principe', 'Africa/Sao_Tome', 2),
 ('Saudi Arabia', 'Asia/Riyadh', 29),
 ('Senegal', 'Africa/Dakar', 9),
 ('Serbia', 'Europe/Belgrade', 3),
 ('Seychelles', 'Indian/Mahe', 3),
 ('Sierra Leone', 'Africa/Freetown', 8),
 ('Singapore', 'Asia/Singapore', 3),
 ('Slovakia', 'Europe/Bratislava', 6),
 ('Slovenia', 'Europe/Ljubljana', 3),
 ('Solomon Islands', 'Pacific/Guadalcanal', 26),
 ('Somalia', 'Africa/Mogadishu', 10),
 ('South Africa', 'Africa/Johannesburg', 48),
 ('South Georgia and the Islands', 'Atlantic/South_Georgia', 0),
 ('South Korea', 'Asia/Seoul', 22),
 ('South Sudan', 'Africa/Juba', 4),
 ('Spain', 'Atlantic/Canary', 8),
 ('Spain', 'Europe/Madrid', 42),
 ('Sri Lanka', 'Asia/Colombo', 13),
 ('Sudan', 'Africa/Khartoum', 10),
 ('Suriname', 'America/Paramaribo', 13),
 ('Swaziland', 'Africa/Mbabane', 1),
 ('Sweden', 'Europe/Stockholm', 54),
 ('Switzerland', 'Europe/Vaduz', 0),
 ('Switzerland', 'Europe/Zurich', 10),
 ('Syria', 'Asia/Damascus', 6),
 ('Taiwan', 'Asia/Taipei', 20),
 ('Tajikistan', 'Asia/Dushanbe', 3),
 ('Tanzania', 'Africa/Dar_es_Salaam', 20),
 ('Thailand', 'Asia/Bangkok', 37),
 ('Togo', 'Africa/Lome', 2),
 ('Tonga', 'Pacific/Tongatapu', 6),
 ('Trinidad and Tobago', 'America/Port_of_Spain', 2),
 ('Tunisia', 'Africa/Tunis', 10),
 ('Turkey', 'Europe/Istanbul', 57),
 ('Turkmenistan', 'Asia/Ashgabat', 6),
 ('Turks and Caicos Islands', 'America/Grand_Turk', 6),
 ('Tuvalu', 'Pacific/Funafuti', 1),
 ('Uganda', 'Africa/Kampala', 6),
 ('Ukraine', 'Europe/Kiev', 31),
 ('United Arab Emirates', 'Asia/Dubai', 11),
 ('United Kingdom', 'Europe/London', 120),
 ('United States', 'America/Anchorage', 239),
 ('United States', 'America/Chicago', 342),
 ('United States', 'America/Denver', 119),
 ('United States', 'America/Los_Angeles', 176),
 ('United States', 'America/New_York', 520),
 ('United States', 'America/Phoenix', 38),
 ('United States', 'Pacific/Honolulu', 18),
 ('Uruguay', 'America/Montevideo', 6),
 ('Uzbekistan', 'Asia/Samarkand', 12),
 ('Vanuatu', 'Pacific/Efate', 29),
 ('Venezuela', 'America/Caracas', 37),
 ('Vietnam', 'Asia/Saigon', 25),
 ('Virgin Islands', 'America/St_Thomas', 3),
 ('Wake Island', 'Pacific/Wake', 1),
 ('Wallis and Futuna', 'Pacific/Wallis', 2),
 ('West Bank', 'Asia/Gaza', 1),
 ('Western Sahara', 'Africa/El_Aaiun', 3),
 ('Yemen', 'Asia/Aden', 10),
 ('Zambia', 'Africa/Lusaka', 8),
 ('Zimbabwe', 'Africa/Harare', 8)]

## Goal 5: Using sql within pandas to filter

`.query()`

[query documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html)

In [72]:
# Get data for an example
import pandas as pd
shelter_data=pd.read_csv('https://data.austintexas.gov/api/views/9t4d-g238/rows.csv?accessType=DOWNLOAD')
shelter_data.dtypes

Animal ID           object
Name                object
DateTime            object
MonthYear           object
Date of Birth       object
Outcome Type        object
Outcome Subtype     object
Animal Type         object
Sex upon Outcome    object
Age upon Outcome    object
Breed               object
Color               object
dtype: object

In [74]:
shelter_data.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A797930,Ranger,06/30/2019 07:24:00 PM,06/30/2019 07:24:00 PM,06/19/2017,Adoption,NaN,Dog,Neutered Male,2 years,Labrador Retriever,Chocolate
1,A794317,*Oreo,06/30/2019 07:14:00 PM,06/30/2019 07:14:00 PM,04/14/2019,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Black/White
2,A797180,Leo,06/30/2019 07:04:00 PM,06/30/2019 07:04:00 PM,06/10/2018,Adoption,NaN,Cat,Neutered Male,1 year,Domestic Medium Hair Mix,Brown Tabby
3,A792953,*Loaf,06/30/2019 07:04:00 PM,06/30/2019 07:04:00 PM,03/17/2019,Adoption,NaN,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Black/White
4,A795729,Laika,06/30/2019 07:00:00 PM,06/30/2019 07:00:00 PM,05/23/2017,Adoption,NaN,Dog,Spayed Female,2 years,German Shepherd,Black/Tan

In [73]:
max_data = shelter_data.query('Name == "Max"')
max_data.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
34,A798743,Max,06/30/2019 04:54:00 PM,06/30/2019 04:54:00 PM,10/29/2018,Return to Owner,NaN,Dog,Intact Male,8 months,Maltese/Miniature Poodle,White/Tan
487,A700767,Max,06/25/2019 02:12:00 PM,06/25/2019 02:12:00 PM,04/19/2011,Return to Owner,NaN,Dog,Neutered Male,8 years,Labrador Retriever/Plott Hound,Brown Brindle/White
799,A797355,Max,06/21/2019 06:39:00 PM,06/21/2019 06:39:00 PM,12/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull Mix,Chocolate/White
811,A797407,Max,06/21/2019 04:05:00 PM,06/21/2019 04:05:00 PM,03/13/2019,Adoption,NaN,Dog,Neutered Male,3 months,German Shepherd/Chinese Sharpei,Tricolor
968,A797258,Max,06/19/2019 12:58:00 PM,06/19/2019 12:58:00 PM,02/11/2018,Transfer,Partner,Dog,Intact Male,1 year,Rottweiler Mix,Black/Tan

In [75]:
#vs
shelter_data[shelter_data['Name']=="Max"]

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
34,A798743,Max,06/30/2019 04:54:00 PM,06/30/2019 04:54:00 PM,10/29/2018,Return to Owner,NaN,Dog,Intact Male,8 months,Maltese/Miniature Poodle,White/Tan
487,A700767,Max,06/25/2019 02:12:00 PM,06/25/2019 02:12:00 PM,04/19/2011,Return to Owner,NaN,Dog,Neutered Male,8 years,Labrador Retriever/Plott Hound,Brown Brindle/White
799,A797355,Max,06/21/2019 06:39:00 PM,06/21/2019 06:39:00 PM,12/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull Mix,Chocolate/White
811,A797407,Max,06/21/2019 04:05:00 PM,06/21/2019 04:05:00 PM,03/13/2019,Adoption,NaN,Dog,Neutered Male,3 months,German Shepherd/Chinese Sharpei,Tricolor
968,A797258,Max,06/19/2019 12:58:00 PM,06/19/2019 12:58:00 PM,02/11/2018,Transfer,Partner,Dog,Intact Male,1 year,Rottweiler Mix,Black/Tan
1036,A797814,Max,06/18/2019 12:52:00 PM,06/18/2019 12:52:00 PM,06/18/2017,Return to Owner,NaN,Dog,Intact Male,2 years,Pug,Tan/Black
1080,A797341,Max,06/17/2019 05:12:00 PM,06/17/2019 05:12:00 PM,03/12/2019,Adoption,NaN,Cat,Neutered Male,3 months,Domestic Shorthair,Cream Tabby/White
1295,A680607,Max,06/14/2019 11:50:00 AM,06/14/2019 11:50:00 AM,04/04/2014,Return to Owner,NaN,Dog,Neutered Male,5 years,Chihuahua Shorthair Mix,Tan/White
1361,A797339,Max,06/13/2019 11:39:00 AM,06/13/2019 11:39:00 AM,06/12/2017,Return to Owner,NaN,Dog,Intact Male,2 years,Welsh Terrier/Miniature Poodle,Tan/Gray
1612,A780200,Max,06/10/2019 10:53:00 AM,06/10/2019 10:53:00 AM,09/11/2014,Rto-Adopt,NaN,Dog,Neutered Male,4 years,German Shepherd Mix,Brown/Black
1636,A793073,Max,06/09/2019 05:52:00 PM,06/09/2019 05:52:00 PM,06/02/2018,Adoption,NaN,Dog,Neutered Male,1 year,Boxer Mix,Brown/Tricolor
1986,A744193,Max,06/04/2019 03:30:00 PM,06/04/2019 03:30:00 PM,09/27/2016,Adoption,NaN,Dog,Neutered Male,2 years,Cairn Terrier Mix,Tan/White
2049,A794951,Max,06/03/2019 07:30:00 PM,06/03/2019 07:30:00 PM,05/14/2017,Rto-Adopt,NaN,Dog,Intact Male,2 years,Labrador Retriever,Red
2208,A796351,Max,06/01/2019 04:18:00 PM,06/01/2019 04:18:00 PM,05/31/2010,Return to Owner,NaN,Cat,Neutered Male,9 years,Domestic Shorthair,Black/White
2339,A795976,Max,05/30/2019 11:20:00 AM,05/30/2019 11:20:00 AM,05/27/2008,Transfer,Partner,Dog,Neutered Male,11 years,Maltese,White
2836,A784016,Max,05/21/2019 03:13:00 PM,05/21/2019 03:13:00 PM,08/10/2018,Return to Owner,NaN,Dog,Intact Male,9 months,Staffordshire Mix,Brown Brindle/White
3637,A443876,Max,05/06/2019 04:56:00 PM,05/06/2019 04:56:00 PM,03/21/2006,Adoption,NaN,Cat,Neutered Male,13 years,Domestic Shorthair Mix,Blue Tabby/White
3963,A793215,Max,04/30/2019 11:49:00 AM,04/30/2019 11:49:00 AM,04/21/2017,Return to Owner,NaN,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,Black/White
4113,A731802,Max,04/26/2019 06:17:00 PM,04/26/2019 06:17:00 PM,07/27/2015,Adoption,NaN,Dog,Neutered Male,3 years,Maltese Mix,White
4114,A789320,Max,04/26/2019 06:01:00 PM,04/26/2019 06:01:00 PM,08/19/2017,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull Mix,White/Black
4452,A793073,Max,04/19/2019 01:55:00 PM,04/19/2019 01:55:00 PM,06/02/2018,Return to Owner,NaN,Dog,Intact Male,10 months,Boxer Mix,Brown/Tricolor
4571,A791972,Max,04/17/2019 01:35:00 PM,04/17/2019 01:35:00 PM,04/03/2018,Transfer,Partner,Dog,Neutered Male,1 year,Golden Retriever/Border Collie,Tan/White
4788,A789119,Max,04/13/2019 12:45:00 PM,04/13/2019 12:45:00 PM,12/17/2014,Adoption,NaN,Dog,Neutered Male,4 years,Catahoula Mix,Red
4859,A787013,Max,04/12/2019 12:53:00 PM,04/12/2019 12:53:00 PM,10/26/2018,Transfer,Partner,Dog,Neutered Male,5 months,German Shepherd Mix,Tricolor
4900,A792391,Max,04/11/2019 12:04:00 PM,04/11/2019 12:04:00 PM,04/10/2016,Return to Owner,NaN,Dog,Intact Male,3 years,American Bulldog/Boxer,White/Brown Brindle
5052,A781808,Max,04/08/2019 02:27:00 PM,04/08/2019 02:27:00 PM,01/01/2018,Return to Owner,NaN,Dog,Neutered Male,1 year,Alaskan Husky,Brown/White
5188,A775940,Max,04/04/2019 09:27:00 PM,04/04/2019 09:27:00 PM,05/04/2018,Adoption,NaN,Dog,Neutered Male,11 months,Plott Hound/Labrador Retriever,Brown Brindle/White
5354,A786674,Max,04/01/2019 06:02:00 PM,04/01/2019 06:02:00 PM,12/29/2016,Rto-Adopt,NaN,Dog,Neutered Male,2 years,Australian Shepherd Mix,Red/White
5405,A791533,Max,03/31/2019 04:19:00 PM,03/31/2019 04:19:00 PM,10/12/2018,Adoption,NaN,Dog,Neutered Male,5 months,Dachshund Mix,Black
5542,A724499,Max,03/27/2019 07:20:00 PM,03/27/2019 07:20:00 PM,04/18/2012,Adoption,NaN,Dog,Neutered Male,6 years,German Shepherd,Sable
...,...,...,...,...,...,...,...,...,...,...,...,...
96224,A648236,Max,02/26/2014 04:50:00 PM,02/26/2014 04:50:00 PM,04/24/2012,Return to Owner,NaN,Dog,Neutered Male,1 year,Australian Cattle Dog Mix,Red Tick/White
96487,A673191,Max,02/20/2014 03:40:00 PM,02/20/2014 03:40:00 PM,02/19/2011,Euthanasia,Rabies Risk,Dog,Intact Male,3 years,Labrador Retriever Mix,Brown/White
96685,A671314,Max,02/16/2014 11:53:00 AM,02/16/2014 11:53:00 AM,03/22/2013,Adoption,NaN,Dog,Neutered Male,10 months,Collie Rough Mix,White/Black
96852,A672335,Max,02/11/2014 06:20:00 PM,02/11/2014 06:20:00 PM,02/08/2012,Return to Owner,NaN,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,Black/Tan
97150,A671503,Max,02/03/2014 06:11:00 PM,02/03/2014 06:11:00 PM,01/25/2012,Adoption,NaN,Dog,Neutered Male,2 years,Beagle/Dachshund,White/Brown
97192,A652954,Max,02/03/2014 11:40:00 AM,02/03/2014 11:40:00 AM,12/17/2012,Adoption,NaN,Dog,Neutered Male,1 year,German Shepherd/Labrador Retriever,Brown/Black
97223,A671583,Max,02/02/2014 02:59:00 PM,02/02/2014 02:59:00 PM,04/01/2013,Adoption,NaN,Dog,Neutered Male,10 months,Wire Hair Fox Terrier Mix,White/Black
97252,A671583,Max,02/01/2014 05:40:00 PM,02/01/2014 05:40:00 PM,04/01/2013,Adoption,NaN,Dog,Neutered Male,10 months,Wire Hair Fox Terrier Mix,White/Black
97942,A670802,Max,01/15/2014 06:53:00 PM,01/15/2014 06:53:00 PM,07/14/2010,Return to Owner,NaN,Dog,Neutered Male,3 years,Labrador Retriever Mix,Tan
98147,A665405,Max,01/10/2014 06:41:00 PM,01/10/2014 06:41:00 PM,06/17/2013,Adoption,NaN,Dog,Neutered Male,6 months,Labrador Retriever Mix,Black/White
98165,A648236,Max,01/10/2014 03:19:00 PM,01/10/2014 03:19:00 PM,04/24/2012,Return to Owner,NaN,Dog,Neutered Male,1 year,Australian Cattle Dog Mix,Red Tick/White
98221,A664369,Max,01/08/2014 07:19:00 PM,01/08/2014 07:19:00 PM,05/27/2013,Return to Owner,NaN,Dog,Neutered Male,7 months,Labrador Retriever/German Shepherd,Black
98326,A669946,Max,01/05/2014 06:11:00 PM,01/05/2014 06:11:00 PM,12/30/2012,Adoption,NaN,Dog,Neutered Male,1 year,Labrador Retriever Mix,Black
98579,A669266,Max,12/31/2013 04:51:00 PM,12/31/2013 04:51:00 PM,07/27/2013,Adoption,NaN,Dog,Neutered Male,5 months,Pit Bull Mix,White/Black Brindle
98994,A522774,Max,12/23/2013 04:45:00 PM,12/23/2013 04:45:00 PM,10/02/2006,Return to Owner,NaN,Dog,Neutered Male,7 years,Chihuahua Shorthair,Tricolor
99112,A669211,Max,12/21/2013 06:25:00 PM,12/21/2013 06:25:00 PM,12/17/2011,Adoption,NaN,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,White/Brown
99226,A669274,Max,12/19/2013 05:10:00 PM,12/19/2013 05:10:00 PM,12/17/2011,Return to Owner,NaN,Dog,Neutered Male,2 years,Cardigan Welsh Corgi Mix,White
99493,A590637,Max,12/14/2013 01:10:00 PM,12/14/2013 01:10:00 PM,12/21/2009,Adoption,NaN,Dog,Neutered Male,3 years,German Shepherd Mix,Tan/White
99538,A668634,Max,12/13/2013 12:10:00 PM,12/13/2013 12:10:00 PM,02/06/2013,Adoption,NaN,Dog,Neutered Male,10 months,Anatol Shepherd/Labrador Retriever,Brown Brindle/White
99731,A668750,Max,12/08/2013 06:13:00 PM,12/08/2013 06:13:00 PM,12/08/2011,Return to Owner,NaN,Dog,Neutered Male,2 years,Basset Hound Mix,Black/White
99771,A668202,Max,12/08/2013 01:01:00 PM,12/08/2013 01:01:00 PM,01/29/2013,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White
100666,A661874,Max,11/17/2013 12:53:00 PM,11/17/2013 12:53:00 PM,06/15/2013,Transfer,Partner,Dog,Neutered Male,5 months,Miniature Schnauzer Mix,Black/White
101381,A605315,Max,11/02/2013 12:08:00 PM,11/02/2013 12:08:00 PM,01/06/2009,Return to Owner,NaN,Dog,Neutered Male,4 years,American Pit Bull Terrier,Black/White
101437,A665263,Max,11/01/2013 11:37:00 AM,11/01/2013 11:37:00 AM,07/31/2013,Adoption,NaN,Dog,Neutered Male,3 months,Labrador Retriever Mix,Black
101471,A665445,Max,10/31/2013 01:03:00 PM,10/31/2013 01:03:00 PM,06/18/2013,Adoption,NaN,Dog,Neutered Male,4 months,Labrador Retriever Mix,Brown/Black
101655,A664692,Max,10/27/2013 02:45:00 PM,10/27/2013 02:45:00 PM,10/07/2007,Transfer,Partner,Cat,Neutered Male,6 years,Russian Blue Mix,Blue
101685,A665743,Max,10/26/2013 06:38:00 PM,10/26/2013 06:38:00 PM,12/22/2012,Adoption,NaN,Dog,Neutered Male,10 months,Jack Russell Terrier/Chihuahua Shorthair,White/Brown
101931,A665405,Max,10/21/2013 04:59:00 PM,10/21/2013 04:59:00 PM,06/17/2013,Adoption,NaN,Dog,Neutered Male,4 months,Labrador Retriever Mix,Black/White
102460,A664369,Max,10/12/2013 06:00:00 PM,10/12/2013 06:00:00 PM,05/27/2013,Return to Owner,NaN,Dog,Neutered Male,4 months,Labrador Retriever/German Shepherd,Black
102468,A662933,Max,10/12/2013 05:13:00 PM,10/12/2013 05:13:00 PM,09/10/2006,Return to Owner,NaN,Dog,Neutered Male,7 years,Pug Mix,Brown/Black

In [76]:
shelter_data.rename(index=str, columns={"Animal Type": "animal_type"}, inplace = True)
test = shelter_data.query('animal_type == "Dog"')
test.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,animal_type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A797930,Ranger,06/30/2019 07:24:00 PM,06/30/2019 07:24:00 PM,06/19/2017,Adoption,NaN,Dog,Neutered Male,2 years,Labrador Retriever,Chocolate
4,A795729,Laika,06/30/2019 07:00:00 PM,06/30/2019 07:00:00 PM,05/23/2017,Adoption,NaN,Dog,Spayed Female,2 years,German Shepherd,Black/Tan
6,A794301,Presley,06/30/2019 06:38:00 PM,06/30/2019 06:38:00 PM,05/06/2018,Adoption,NaN,Dog,Spayed Female,1 year,Border Collie Mix,Tricolor
9,A798764,NaN,06/30/2019 06:35:00 PM,06/30/2019 06:35:00 PM,03/02/2019,Transfer,Partner,Dog,Intact Female,3 months,Pit Bull Mix,Black/White
10,A790523,Bordeaux,06/30/2019 06:24:00 PM,06/30/2019 06:24:00 PM,03/11/2018,Adoption,NaN,Dog,Intact Male,1 year,Boxer Mix,Brown/White

## Goal 6: Transfering from sqlite to pandas

In [77]:
conn = sqlite3.connect("flights.db")
df = pd.read_sql_query("select * from airports limit 5;", conn)
df

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10,U,Pacific/Port_Moresby
1,1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.7887,20,10,U,Pacific/Port_Moresby
2,2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10,U,Pacific/Port_Moresby
3,3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10,U,Pacific/Port_Moresby
4,4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.22005,146,10,U,Pacific/Port_Moresby

**Task**: 
Convert one of the earlier queries in the lesson to a pandas data frame

In [78]:
df1 = pd.read_sql_query('''select country, timezone, count(code) as cc from airports 
                  group by timezone order by country;''', conn)
df1

                      country               timezone   cc
0                 Afghanistan             Asia/Kabul   16
1                     Albania          Europe/Tirane    1
2                     Algeria         Africa/Algiers   35
3              American Samoa      Pacific/Pago_Pago    3
4                      Angola          Africa/Luanda   22
5                    Anguilla       America/Anguilla    1
6                  Antarctica  Antarctica/South_Pole    0
7         Antigua and Barbuda        America/Antigua    2
8                   Argentina        America/Cordoba   72
9                     Armenia           Asia/Yerevan    2
10                      Aruba          America/Aruba    1
11                  Australia     Australia/Adelaide   15
12                  Australia     Australia/Brisbane   70
13                  Australia       Australia/Darwin   21
14                  Australia       Australia/Hobart   12
15                  Australia    Australia/Melbourne    7
16                  Australia        Australia/Perth   36
17                  Australia       Australia/Sydney   45
18                    Austria          Europe/Vienna    9
19                 Azerbaijan              Asia/Baku    7
20                    Bahamas         America/Nassau   25
21                    Bahrain           Asia/Bahrain    1
22                 Bangladesh             Asia/Dhaka    9
23                   Barbados       America/Barbados    1
24                    Belarus           Europe/Minsk    6
25                    Belgium        Europe/Brussels   10
26                     Belize         America/Belize   12
27                      Benin      Africa/Porto-Novo    1
28                    Bermuda       Atlantic/Bermuda    1
29                     Bhutan           Asia/Thimphu    1
..                        ...                    ...  ...
264       Trinidad and Tobago  America/Port_of_Spain    2
265                   Tunisia           Africa/Tunis   10
266                    Turkey        Europe/Istanbul   57
267              Turkmenistan          Asia/Ashgabat    6
268  Turks and Caicos Islands     America/Grand_Turk    6
269                    Tuvalu       Pacific/Funafuti    1
270                    Uganda         Africa/Kampala    6
271                   Ukraine            Europe/Kiev   31
272      United Arab Emirates             Asia/Dubai   11
273            United Kingdom          Europe/London  120
274             United States      America/Anchorage  239
275             United States        America/Chicago  342
276             United States         America/Denver  119
277             United States    America/Los_Angeles  176
278             United States       America/New_York  520
279             United States        America/Phoenix   38
280             United States       Pacific/Honolulu   18
281                   Uruguay     America/Montevideo    6
282                Uzbekistan         Asia/Samarkand   12
283                   Vanuatu          Pacific/Efate   29
284                 Venezuela        America/Caracas   37
285                   Vietnam            Asia/Saigon   25
286            Virgin Islands      America/St_Thomas    3
287               Wake Island           Pacific/Wake    1
288         Wallis and Futuna         Pacific/Wallis    2
289                 West Bank              Asia/Gaza    1
290            Western Sahara        Africa/El_Aaiun    3
291                     Yemen              Asia/Aden   10
292                    Zambia          Africa/Lusaka    8
293                  Zimbabwe          Africa/Harare    8

[294 rows x 3 columns]

## Integration

The [Chinook database](https://github.com/lerocha/chinook-database) is a sample database, representing a digital media store.

You need to create a query that can rank tracks in term of popularity.

The name of the database is `Chinook_Sqlite.sqlite`

Database information:<br>
- How many tables are in the database?
- What's the primary key of each table?
- What foreign keys join the tables together?
- If you had to draw a schema of how the tables are connected, what would it look like?

To answer the question:<br>
- What are the max and min dates in the Invoice table?
- What tables would you need to answer "what is your most popular track?"
- What values from each table?

In [79]:
conn = sqlite3.connect('Chinook_Sqlite.sqlite')
c = conn.cursor()

In [80]:
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(c.fetchall())

[('Album',), ('Artist',), ('Customer',), ('Employee',), ('Genre',), ('Invoice',), ('InvoiceLine',), ('MediaType',), ('Playlist',), ('PlaylistTrack',), ('Track',)]

In [81]:
c.execute("SELECT name, type FROM sqlite_master;")
print(c.fetchall())

[('Album', 'table'), ('Artist', 'table'), ('Customer', 'table'), ('Employee', 'table'), ('Genre', 'table'), ('Invoice', 'table'), ('InvoiceLine', 'table'), ('MediaType', 'table'), ('Playlist', 'table'), ('PlaylistTrack', 'table'), ('sqlite_autoindex_PlaylistTrack_1', 'index'), ('Track', 'table'), ('IPK_Album', 'index'), ('IPK_Artist', 'index'), ('IPK_Customer', 'index'), ('IPK_Employee', 'index'), ('IPK_Genre', 'index'), ('IPK_Invoice', 'index'), ('IPK_InvoiceLine', 'index'), ('IPK_MediaType', 'index'), ('IPK_Playlist', 'index'), ('IPK_PlaylistTrack', 'index'), ('IPK_Track', 'index'), ('IFK_AlbumArtistId', 'index'), ('IFK_CustomerSupportRepId', 'index'), ('IFK_EmployeeReportsTo', 'index'), ('IFK_InvoiceCustomerId', 'index'), ('IFK_InvoiceLineInvoiceId', 'index'), ('IFK_InvoiceLineTrackId', 'index'), ('IFK_PlaylistTrackTrackId', 'index'), ('IFK_TrackAlbumId', 'index'), ('IFK_TrackGenreId', 'index'), ('IFK_TrackMediaTypeId', 'index')]

In [84]:
c.execute("SELECT count(type) FROM sqlite_master where type= 'table';").fetchall()

[(11,)]

In [92]:
tables = c.execute("SELECT name FROM sqlite_master where type= 'table';").fetchall()
tlist = []
for t in tables:
    tlist.append(t[0].replace('''''''', ''))
tlist

['Album',
 'Artist',
 'Customer',
 'Employee',
 'Genre',
 'Invoice',
 'InvoiceLine',
 'MediaType',
 'Playlist',
 'PlaylistTrack',
 'Track']

In [88]:
tlist[0]

'Album'

In [94]:
c.execute("PRAGMA table_info(Album)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'AlbumId', 'INTEGER', 1, None, 1)
(1, 'Title', 'NVARCHAR(160)', 1, None, 0)
(2, 'ArtistId', 'INTEGER', 1, None, 0)

In [95]:
c.execute("PRAGMA table_info(artist)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'ArtistId', 'INTEGER', 1, None, 1)
(1, 'Name', 'NVARCHAR(120)', 0, None, 0)

In [96]:
c.execute("PRAGMA table_info(invoice)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'InvoiceId', 'INTEGER', 1, None, 1)
(1, 'CustomerId', 'INTEGER', 1, None, 0)
(2, 'InvoiceDate', 'DATETIME', 1, None, 0)
(3, 'BillingAddress', 'NVARCHAR(70)', 0, None, 0)
(4, 'BillingCity', 'NVARCHAR(40)', 0, None, 0)
(5, 'BillingState', 'NVARCHAR(40)', 0, None, 0)
(6, 'BillingCountry', 'NVARCHAR(40)', 0, None, 0)
(7, 'BillingPostalCode', 'NVARCHAR(10)', 0, None, 0)
(8, 'Total', 'NUMERIC(10,2)', 1, None, 0)

In [102]:
c.execute("PRAGMA table_info(invoiceline)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'InvoiceLineId', 'INTEGER', 1, None, 1)
(1, 'InvoiceId', 'INTEGER', 1, None, 0)
(2, 'TrackId', 'INTEGER', 1, None, 0)
(3, 'UnitPrice', 'NUMERIC(10,2)', 1, None, 0)
(4, 'Quantity', 'INTEGER', 1, None, 0)

In [103]:
c.execute("select * from invoiceline;").fetchmany(5)

[(1, 1, 2, 0.99, 1),
 (2, 1, 4, 0.99, 1),
 (3, 2, 6, 0.99, 1),
 (4, 2, 8, 0.99, 1),
 (5, 2, 10, 0.99, 1)]

In [99]:
c.execute("PRAGMA table_info(playlisttrack)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'PlaylistId', 'INTEGER', 1, None, 1)
(1, 'TrackId', 'INTEGER', 1, None, 2)

In [101]:
c.execute("PRAGMA table_info(playlist)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'PlaylistId', 'INTEGER', 1, None, 1)
(1, 'Name', 'NVARCHAR(120)', 0, None, 0)

In [100]:
c.execute("PRAGMA table_info(track)")
info = c.fetchall()
print(*info, sep = "\n")

(0, 'TrackId', 'INTEGER', 1, None, 1)
(1, 'Name', 'NVARCHAR(200)', 1, None, 0)
(2, 'AlbumId', 'INTEGER', 0, None, 0)
(3, 'MediaTypeId', 'INTEGER', 1, None, 0)
(4, 'GenreId', 'INTEGER', 0, None, 0)
(5, 'Composer', 'NVARCHAR(220)', 0, None, 0)
(6, 'Milliseconds', 'INTEGER', 1, None, 0)
(7, 'Bytes', 'INTEGER', 0, None, 0)
(8, 'UnitPrice', 'NUMERIC(10,2)', 1, None, 0)

In [97]:
c.execute('''select max(invoicedate) from invoice;''').fetchall()

[('2013-12-22 00:00:00',)]

In [98]:
c.execute('''select min(invoicedate) from invoice;''').fetchall()

[('2009-01-01 00:00:00',)]

In [108]:
c.execute('''select sum(quantity) as q, name from invoiceline join track using(trackid) group by name order by q desc;''').fetchall()

[(5, 'The Trooper'),
 (4, 'Eruption'),
 (4, 'Hallowed Be Thy Name'),
 (4, 'Sure Know Something'),
 (4, 'The Number Of The Beast'),
 (4, 'Untitled'),
 (3, '2 Minutes To Midnight'),
 (3, 'Blood Brothers'),
 (3, 'Brasil'),
 (3, 'Can I Play With Madness'),
 (3, 'Dazed and Confused'),
 (3, 'Flying High Again'),
 (3, 'Good Golly Miss Molly'),
 (3, 'Heaven Can Wait'),
 (3, 'Iron Maiden'),
 (3, 'Linha Do Equador'),
 (3, 'Plaster Caster'),
 (3, 'Release'),
 (3, 'Sanctuary'),
 (3, 'Selvagem'),
 (3, 'Stairway To Heaven'),
 (3, 'Surrender'),
 (3, 'Sweetest Thing'),
 (3, 'Welcome Home (Sanitarium)'),
 (3, 'Where Eagles Dare'),
 (2, 'A Cor Do Sol'),
 (2, 'A Melhor Forma'),
 (2, 'A Novidade (Live)'),
 (2, 'Abraham, Martin And John'),
 (2, 'Acelerou'),
 (2, 'Aces High'),
 (2, 'Afraid To Shoot Strangers'),
 (2, 'All Along The Watchtower'),
 (2, 'All I Want Is You'),
 (2, 'Amor De Muito'),
 (2, 'Ando Meio Desligado'),
 (2, 'Animal'),
 (2, 'As Rosas Não Falam (Beth Carvalho)'),
 (2, 'Azul'),
 (2, 'Açai'),
 (2, 'Babylon'),
 (2, 'Balls to the Wall'),
 (2, 'Banditismo Por Uma Questa'),
 (2, 'Basket Case'),
 (2, 'Battery'),
 (2, 'Beautiful Boy'),
 (2, 'Before You Accuse Me'),
 (2, 'Beira Mar'),
 (2, 'Believe'),
 (2, 'Bem Devagar'),
 (2, 'Better Than You'),
 (2, 'Big Wave'),
 (2, 'Binky The Doormat'),
 (2, 'Black Dog'),
 (2, 'Blue Rythm Fantasy'),
 (2, 'Boris The Spider'),
 (2, 'Bowels Of The Devil'),
 (2, 'Branch Closing'),
 (2, 'Breakdown'),
 (2, 'Bron-Y-Aur Stomp'),
 (2, 'Bullet With Butterfly Wings'),
 (2, 'Bumbo Da Mangueira'),
 (2, "C'est La Vie"),
 (2, 'Cabeça Dinossauro'),
 (2, 'Caffeine'),
 (2, 'Caleidoscópio'),
 (2, 'Calling Dr. Love'),
 (2, 'Celebration Day'),
 (2, 'Chemical Wedding'),
 (2, 'Cherub Rock'),
 (2, 'Children Of The Grave'),
 (2, 'City Of Blinding Lights'),
 (2, 'Comida'),
 (2, "Comin' Home"),
 (2, 'Commotion'),
 (2, 'Communication Breakdown'),
 (2, 'Compadre'),
 (2, 'Comportamento Geral'),
 (2, 'Cornucopia'),
 (2, 'Country Feedback'),
 (2, 'Dancing Days'),
 (2, 'Dazed And Confused'),
 (2, 'Desire'),
 (2, 'Deuces Are Wild'),
 (2, 'Dezesseis'),
 (2, 'Dirty Day'),
 (2, 'Dois Pra Lá, Dois Pra Cá'),
 (2, "Don't Look Now"),
 (2, "Don't Look To The Eyes Of A Stranger"),
 (2, "Don't Take Your Love From Me"),
 (2, 'Down by the Sea'),
 (2, 'Dream Of Mirrors'),
 (2, 'Drifter'),
 (2, 'Drum Boogie'),
 (2, 'Easy'),
 (2, 'End Of Romanticism'),
 (2, 'Esporrei Na Manivela'),
 (2, 'Esquinas'),
 (2, 'Everlasting Love'),
 (2, 'Falamansa Song'),
 (2, 'Fall On Me'),
 (2, 'Fear Of The Dark'),
 (2, 'Firmamento'),
 (2, 'Folhas Secas'),
 (2, 'For Whom The Bell Tolls'),
 (2, 'For Your Life'),
 (2, 'For the Greater Good of God'),
 (2, 'Gangland'),
 (2, 'Garden of Eden'),
 (2, 'Gay Witch Hunt'),
 (2, 'Geni E O Zepelim'),
 (2, 'Get Up'),
 (2, 'Ghost Of The Navigator'),
 (2, 'Gimme Some Truth'),
 (2, 'Give Me Novacaine'),
 (2, 'Give Peace a Chance'),
 (2, 'Gyroscope'),
 (2, 'Hallelujah Here She Comes'),
 (2, 'Heaven Coming Down'),
 (2, 'Helpless'),
 (2, 'Hey America'),
 (2, 'Holiday'),
 (2, 'Hot Girl'),
 (2, 'How Many More Times'),
 (2, 'How to Stop an Exploding Man'),
 (2, 'I Believe'),
 (2, "I Can't Explain"),
 (2, "I'm Going Slightly Mad"),
 (2, "I'm Gonna Crawl"),
 (2, 'Imagine'),
 (2, 'Immigrant Song'),
 (2, 'In The Evening'),
 (2, 'Inject The Venom'),
 (2, 'Intro'),
 (2, 'Is This Love (Live)'),
 (2, 'J Squared'),
 (2, 'Judgement Of Heaven'),
 (2, 'Já Foi'),
 (2, 'King For A Day'),
 (2, "L'Arc En Ciel De Miles"),
 (2, "L'Avventura"),
 (2, 'Lamento De Carnaval'),
 (2, 'Last Cup Of Sorrow'),
 (2, 'Lay Down Sally'),
 (2, 'Layla'),
 (2, 'Leave My Girl Alone'),
 (2, 'Lemon Drop'),
 (2, 'Leper Messiah'),
 (2, 'Let Me Love You Baby'),
 (2, 'Light Years'),
 (2, "Living Loving Maid (She's Just A Woman)"),
 (2, 'Living On Love'),
 (2, 'Lixo Do Mangue'),
 (2, 'Lonely Stranger'),
 (2, 'Lugar Nenhum'),
 (2, "Mama, I'm Coming Home"),
 (2, 'Manguetown'),
 (2, 'Master Of Puppets'),
 (2, "Maybe I'm A Leo"),
 (2, 'Meditação'),
 (2, 'Mel'),
 (2, 'Menestrel Das Alagoas'),
 (2, 'Menino De Rua'),
 (2, 'Mensagen De Amor (2000)'),
 (2, 'Meu Caro Amigo'),
 (2, 'Meu Erro'),
 (2, 'Miami'),
 (2, 'Midlife Crisis'),
 (2, 'Midnight From The Inside Out'),
 (2, 'Mis Penas Lloraba Yo (Ao Vivo) Soy Gitano (Tangos)'),
 (2, 'Moonchild'),
 (2, 'Morena De Angola'),
 (2, 'Motorbreath'),
 (2, 'Mr. Cab Driver'),
 (2,
  'Music for the Funeral of Queen Mary: VI. "Thou Knowest, Lord, the Secrets of Our Hearts"'),
 (2, 'Música No Ar'),
 (2, 'Nebulosa Do Amor'),
 (2, 'Nega Do Cabelo Duro'),
 (2, "New Year's Day"),
 (2, 'Nice Guys Finish Last'),
 (2, 'No No No'),
 (2, 'No Quarter'),
 (2, 'Norwegian Wood'),
 (2, 'Nossa Gente (Avisa Là)'),
 (2, 'Not The Doctor'),
 (2, 'Nothing Else Matters'),
 (2, 'Não Quero Dinheiro'),
 (2, 'O Pulso'),
 (2, 'Onde Anda Você'),
 (2, 'Onde Você Mora?'),
 (2, 'Overdose'),
 (2, 'Paint It Black'),
 (2, 'Peace On Earth'),
 (2, 'Pela Luz dos Olhos Teus (Miúcha e Tom Jobim)'),
 (2, 'Perfect Crime'),
 (2, 'Phantom Lord'),
 (2, "Phyllis's Wedding"),
 (2, 'Piece Of Pie'),
 (2, 'Pilot'),
 (2, 'Plot 180'),
 (2, 'Polly'),
 (2, 'Por Causa De Você'),
 (2, 'Powerslave'),
 (2, 'Pretty Noose'),
 (2, 'Pride (In The Name Of Love)'),
 (2, 'Primavera'),
 (2, 'Promises'),
 (2, 'Prowler'),
 (2, 'Que Luz É Essa'),
 (2, 'Question!'),
 (2, 'Radio Song'),
 (2, 'Ramble On'),
 (2, 'Rappers Reais'),
 (2, 'Re-Align'),
 (2, 'Real Love'),
 (2, 'Red Light'),
 (2, 'Rehab'),
 (2, 'Revolta Olodum'),
 (2, 'Right On Time'),
 (2, 'Rock & Roll'),
 (2, 'Rock And Roll All Nite'),
 (2, 'Rocket Queen'),
 (2, 'Romance Ideal'),
 (2, 'Run Silent Run Deep'),
 (2, 'Run To The Hills'),
 (2, 'Saber Amar'),
 (2, 'Samba De Orly'),
 (2, 'Samba Do Lado'),
 (2, 'Sangue Latino'),
 (2, 'Saturnine'),
 (2, 'Save The Children'),
 (2, "Scheherazade, Op. 35: I. The Sea and Sindbad's Ship"),
 (2, 'Shakes and Ladders'),
 (2, 'She'),
 (2, 'She Loves Me Not'),
 (2, 'Shock Me'),
 (2, 'Shoot Me Again'),
 (2, 'Sign Of The Cross'),
 (2, "Since I've Been Loving You"),
 (2, 'Slither'),
 (2, 'Smells Like Teen Spirit'),
 (2, 'Smoke On The Water'),
 (2, 'Snowballed'),
 (2, 'Snowblind'),
 (2, 'So Central Rain'),
 (2, 'So What'),
 (2, 'Soldier Side - Intro'),
 (2, 'Somebody To Love'),
 (2, 'Speed Of Light'),
 (2, 'Starburst'),
 (2, 'Stir It Up (Live)'),
 (2, 'Stone Cold Crazy'),
 (2, 'Stormbringer'),
 (2,
  'String Quartet No. 12 in C Minor, D. 703 "Quartettsatz": II. Andante - Allegro assai'),
 (2, 'Suite No. 3 in D, BWV 1068: III. Gavotte I & II'),
 (2, 'Sun King'),
 (2, 'Sunday Bloody Sunday'),
 (2, 'Sunshine Of Your Love'),
 (2, 'Susie Q'),
 (2, 'Sweet Hitch-Hiker'),
 (2, "Symphonie Fantastique, Op. 14: V. Songe d'une nuit du sabbat"),
 (2, 'Só Tinha De Ser Com Você'),
 (2, 'Take It Or Leave It'),
 (2, 'Tanto Tempo'),
 (2, 'Tarde Em Itapoã'),
 (2, 'Tear'),
 (2, 'Tempo Perdido'),
 (2, 'Thank You'),
 (2, "That's The Way"),
 (2, 'The Aftermath'),
 (2, 'The Clairvoyant'),
 (2, 'The Duke'),
 (2, 'The Evil That Men Do'),
 (2, 'The Fix'),
 (2, 'The Garden'),
 (2, 'The House Jack Built'),
 (2, 'The Last Song'),
 (2, 'The Midnight Special'),
 (2, 'The Prisoner'),
 (2, 'The Star Spangled Banner'),
 (2, 'The Thin Line Between Love & Hate'),
 (2, 'The Unforgiven'),
 (2, 'The Unforgiven II'),
 (2, 'The Wicker Man'),
 (2, 'The Woman King'),
 (2, 'Times Like These'),
 (2, 'Title Song'),
 (2, 'Toda Cor'),
 (2, 'Train In Vain'),
 (2, 'Travis Walk'),
 (2, 'Turbo Lover'),
 (2, 'Two Hearts Beat As One'),
 (2, 'Um Amor Puro'),
 (2, 'Under The Bridge'),
 (2, 'Undertow'),
 (2, 'Violent Pornography'),
 (2, 'Voodoo'),
 (2, 'Waiting'),
 (2, 'Walkabout'),
 (2, 'Walking Into Clarksdale'),
 (2, "Walter's Walk"),
 (2, 'War Pigs'),
 (2, 'We Are The Champions'),
 (2, 'What A Day'),
 (2, "Whatever It Is, I Just Can't Stop"),
 (2, 'Whatsername'),
 (2, 'When I Come Around'),
 (2, 'When I Look At The World'),
 (2, 'When Love Comes To Town'),
 (2, 'When My Left Eye Jumps'),
 (2, 'Whiskey In The Jar'),
 (2, 'Woman Is The Nigger Of The World (Ao Vivo)'),
 (2, 'Wrathchild'),
 (2, 'Year to the Day'),
 (2, 'You Better You Bet'),
 (2, 'You Got Me Rocking'),
 (2, "You're My Best Friend"),
 (2, "You've Got Another Thing Comin'"),
 (2, 'Your Time Is Gonna Come'),
 (2, 'Álibi'),
 (1, '"?"'),
 (1, '#9 Dream'),
 (1, "'Round Midnight"),
 (1, '(Anesthesia) Pulling Teeth'),
 (1, '(White Man) In Hammersmith Palais'),
 (1, '(Wish I Could) Hideaway'),
 (1, '...And Found'),
 (1, '...And Justice For All'),
 (1, '01 - Prowler'),
 (1, '04 - Running Free'),
 (1, '05 - Phantom of the Opera'),
 (1, '09 - Iron Maiden'),
 (1, '1/2 Full'),
 (1, '14 Years'),
 (1, '2 A.M.'),
 (1, '2 X 4'),
 (1, '32 Dentes'),
 (1, '5.15'),
 (1, 'A Banda'),
 (1, 'A Bencao E Outros'),
 (1, 'A Benihana Christmas, Pts. 1 & 2'),
 (1, 'A Cura'),
 (1, 'A Day In the Life'),
 (1, 'A Festa Do Santo Reis'),
 (1, 'A Kind Of Magic'),
 (1, 'A Man And A Woman'),
 (1, 'A Menina Dança'),
 (1, "A Midsummer Night's Dream, Op.61 Incidental Music: No.7 Notturno"),
 (1, 'A Moça e a Chuva'),
 (1, 'A Noite Do Meu Bem'),
 (1, 'A Paz'),
 (1, 'A Small Victory'),
 (1, 'A Statistic'),
 (1, 'A Sua'),
 (1, 'A Touch Away'),
 (1, 'A Twist In The Tail'),
 (1, 'A.N.D.R.O.T.A.Z.'),
 (1, 'Abrir A Porta'),
 (1, 'Achilles Last Stand'),
 (1, 'Acrobat'),
 (1, 'Act IV, Symphony'),
 (1, 'Action'),
 (1, 'Adios nonino'),
 (1, 'Admirável Gado Novo'),
 (1, 'Adrift'),
 (1, 'Advance Romance'),
 (1, 'Aeroplane Flies High'),
 (1, 'After Midnight'),
 (1, 'Age Of Innocence'),
 (1, 'Agora Que O Dia Acordou'),
 (1, "Ain't My Bitch"),
 (1, "Ain't Talkin' 'bout Love"),
 (1, 'Alberta'),
 (1, 'Ali'),
 (1, 'Alive'),
 (1, 'All Because Of You'),
 (1, 'All Dead, All Dead'),
 (1, 'All For You'),
 (1, 'All I Really Want'),
 (1, 'All My Love'),
 (1, 'All Night Thing'),
 (1, 'All Star'),
 (1, 'All Within My Hands'),
 (1, 'Aloha'),
 (1, 'Always With Me, Always With You'),
 (1, 'Alô, Alô, Marciano'),
 (1, 'Am I Evil?'),
 (1, 'Amanhã Não Se Sabe'),
 (1, 'Amazing'),
 (1, 'American Idiot'),
 (1, 'American Woman'),
 (1, 'Amor Demais'),
 (1, 'Amy Amy Amy (Outro)'),
 (1, 'Angel'),
 (1, 'Angel Of Harlem'),
 (1, 'Angela'),
 (1, 'Another Life'),
 (1, 'Another One Bites The Dust'),
 (1, 'Anthem'),
 (1, 'Any Colour You Like'),
 (1, 'Anything Goes'),
 (1, 'Anyway, Anyhow, Anywhere'),
 (1, 'Aos Leões'),
 (1, 'Apesar De Você'),
 (1, 'Aprendendo A Jogar'),
 (1, 'Aquele Abraço'),
 (1, 'Aquilo'),
 (1, 'Arc'),
 (1, 'Are We The Waiting'),
 (1, 'Are You Gonna Be My Girl'),
 (1, 'Are You Gonna Go My Way'),
 (1, 'Armadura'),
 (1, 'Army Ants'),
 (1, 'Around The World'),
 (1, 'As Aparências Enganam'),
 (1, 'As Dores do Mundo'),
 (1, 'As Profecias'),
 (1, 'As Tears Go By'),
 (1, 'As We Sleep'),
 (1, 'Ashes To Ashes'),
 (1, 'Assaltaram A Gramática'),
 (1, 'Assim Caminha A Humanidade'),
 (1, 'Assum Preto'),
 (1, 'Astronomy'),
 (1, 'Atomic Punk'),
 (1, 'Atras Da Porta'),
 (1, 'Atrás Da Verd-E-Rosa Só Não Vai Quem Já Morreu'),
 (1, 'Atrás da Porta'),
 (1, 'Attitude'),
 (1, 'Ava Adore'),
 (1, 'Avisa'),
 (1, 'B.Y.O.B.'),
 (1, "Baba O'Riley"),
 (1, 'Babyface'),
 (1, 'Back Door Man'),
 (1, 'Back from Vacation'),
 (1, 'Back in the Village'),
 (1, 'Back off Bitch'),
 (1, 'Back to Black'),
 (1, 'Bad'),
 (1, 'Bad Moon Rising'),
 (1, 'Bad Obsession'),
 (1, 'Bad Seed'),
 (1, 'Bad, Bad Leroy Brown'),
 (1, 'Badge'),
 (1, 'Balanço'),
 (1, "Baltar's Escape"),
 (1, 'Baltimore, DC'),
 (1, 'Bankrobber'),
 (1, 'Bark at the Moon'),
 (1, 'Bass Trap'),
 (1, 'Battlestar Galactica, Pt. 1'),
 (1, 'Battlestar Galactica, Pt. 2'),
 (1, 'Be Aggressive'),
 (1, 'Be Good Johnny'),
 (1, 'Be Mine'),
 (1, 'Beach Sequence'),
 (1, 'Been A Son'),
 (1, 'Beija-Flor'),
 (1, 'Beijo Partido'),
 (1, 'Believer'),
 (1, 'Bell Bottom Blues'),
 (1, 'Berimbau'),
 (1, 'Best Thing'),
 (1, 'Beth'),
 (1, 'Better Halves'),
 (1, 'Bicycle Race'),
 (1, 'Big Machine'),
 (1, 'Billie Jean'),
 (1, 'Bittersweet Me'),
 (1, 'Black'),
 (1, 'Black Capricorn Day'),
 (1, 'Black Diamond'),
 (1, 'Black Hole Sun'),
 (1, 'Black Light Syndrome'),
 (1, 'Black Moon Creeping'),
 (1, 'Black Mountain Side'),
 (1, 'Black Night'),
 (1, 'Black Satin'),
 (1, 'Blackened'),
 (1, 'Bleed The Freak'),
 (1, 'Bleed Together'),
 (1, 'Bleeding Me'),
 (1, 'Blind Man'),
 (1, 'Blissed & Gone'),
 (1, 'Blitzkrieg'),
 (1, 'Blood In The Wall'),
 (1, "Blood On The World's Hands"),
 (1, 'Blow Your Mind'),
 (1, 'Blue Train'),
 (1, 'Blues For Pablo (Alternate Take)'),
 (1, 'Body Count'),
 (1, 'Body Count Anthem'),
 (1, "Body Count's In The House"),
 (1, 'Bohemian Rhapsody'),
 (1, 'Boogie Blues'),
 (1, 'Boogie With Stu'),
 (1, 'Book Of Thel'),
 (1, 'Bop Boogie'),
 (1, 'Bora-Bora'),
 (1, 'Bored To Tears'),
 (1, 'Born On The Bayou'),
 (1, 'Born To Move'),
 (1, 'Born to Run'),
 (1, 'Bossa'),
 (1, 'Boulevard Of Broken Dreams'),
 (1, 'Brain Damage'),
 (1, 'Brain Stew'),
 (1, 'Brasília 5:31'),
 (1, 'Brave New World'),
 (1, 'Breadfan'),
 (1, 'Breaking The Rules'),
 (1, 'Breakthru'),
 (1, 'Breathe'),
 (1, 'Breed'),
 (1, 'Brighter Than a Thousand Suns'),
 (1, 'Bring Me Your Cup'),
 (1, 'Bring Your Daughter... ...To The Slaughter'),
 (1, 'Bring Your Daughter... To The Slaughter'),
 (1, 'Brumário'),
 (1, 'Bullet The Blue Sky'),
 (1, 'Burden In My Hand'),
 (1, 'Burn Away'),
 (1, 'Busca Vida'),
 (1, 'Bush Doctor'),
 (1, 'By The Way'),
 (1, 'Bye Bye Blackbird'),
 (1, 'Bye, Bye Brasil'),
 (1, 'Bê-a-Bá'),
 (1, "C'Mon Everybody"),
 (1, 'Cafezinho'),
 (1, 'Californication'),
 (1, 'Call Me a Dog'),
 (1, 'Camarão que Dorme e Onda Leva'),
 (1, 'Camisa Verde 2001'),
 (1, 'Can You See Me'),
 (1, "Can't Get There From Here"),
 (1, "Can't Keep"),
 (1, "Can't Stand Losing You"),
 (1, "Can't Stop"),
 (1, "Can't Stop Loving You"),
 (1, 'Canon and Gigue in D Major: I. Canon'),
 (1, 'Canta, Canta Mais'),
 (1, 'Canto De Ossanha'),
 (1, 'Canário Do Reino'),
 (1, 'Caprichosos'),
 (1, 'Caras Como Eu'),
 (1, 'Carnival Of Sorts'),
 (1, 'Carol'),
 (1, 'Carolina'),
 (1, 'Carolina Hard-Core Ecstasy'),
 (1, 'Carouselambra'),
 (1, 'Carta Ao Tom 74'),
 (1, 'Casa'),
 (1, 'Casa no Campo'),
 (1, "Cascades : I'm Not Your Lover"),
 (1, 'Caso Você Queira Saber'),
 (1, 'Catch-22'),
 (1, 'Cathedral'),
 (1, 'Caught Somewhere in Time'),
 (1, 'Caçador de Mim (Sá & Guarabyra)'),
 (1, 'Chains Of Misery'),
 (1, 'Changes'),
 (1, 'Chaos-Control'),
 (1, 'Chapa o Coco'),
 (1, 'Charles Anjo 45'),
 (1, 'Chega no Suingue'),
 (1, 'Child In Time'),
 (1, 'Childhoods End?'),
 (1, 'Children of the Damned'),
 (1, 'Christmas Party'),
 (1, 'Chão De Estrelas'),
 (1, 'Chão de Giz (Elba Ramalho)'),
 (1, 'Cigano'),
 (1, 'Cigaro'),
 (1, 'Cinema Mudo'),
 (1, 'Civil War'),
 (1, 'Clash City Rockers'),
 (1, 'Closer To The Heart'),
 (1, 'Cochise'),
 (1, 'Cold Gin'),
 (1, 'Cold Turkey'),
 (1, 'Colibri'),
 (1, 'Collaborators'),
 (1, 'Com Açúcar E Com Afeto'),
 (1, 'Coma'),
 (1, 'Come Fly With Me'),
 (1, 'Começaria Tudo Outra Vez'),
 (1, 'Commercial 2'),
 (1, 'Communication Breakdown(2)'),
 (1, 'Como Estais Amigos'),
 (1, 'Como É Duro Trabalhar'),
 (1, 'Company Man'),
 (1, 'Compulsion'),
 (1, 'Computadores Fazem Arte'),
 (1, 'Concerto No.2 in F Major, BWV1047, I. Allegro'),
 (1,
  'Concerto for Cello and Orchestra in E minor, Op. 85: I. Adagio - Moderato'),
 (1, 'Concerto for Piano No. 2 in F Minor, Op. 21: II. Larghetto'),
 (1, 'Condição'),
 (1, 'Confusion'),
 (1, 'Construção / Deus Lhe Pague'),
 (1, 'Copacabana (Live)'),
 (1, 'Coração De Estudante'),
 (1, 'Coração Em Desalinho'),
 (1, 'Coração do Agreste (Fafá de Belém)'),
 (1, 'Corduroy'),
 (1, 'Corinna'),
 (1, 'Coroné Antonio Bento'),
 (1, 'Cotton Fields'),
 (1, 'Crackerman'),
 (1, 'Crash Course In Brain Surgery'),
 (1, 'Crazy Train'),
 (1, 'Creep'),
 (1, 'Creeping Death'),
 (1, 'Criança De Domingo'),
 (1, 'Cristina Nº 2'),
 (1, 'Cropduster'),
 (1, 'Crossfire'),
 (1, 'Crossroads'),
 (1, 'Crossroads, Pt. 1'),
 (1, 'Crossroads, Pt. 2'),
 (1, 'Crumbs From Your Table'),
 (1, 'Cry For Love'),
 (1, 'Crystal Ball'),
 (1, 'Cuckoo For Caca'),
 (1, 'Cure'),
 (1, 'Cursed Diamonds'),
 (1, 'Cuyahoga'),
 (1, 'Cérebro Eletrônico'),
 (1, "D'Yer Mak'er"),
 (1, 'Da Lama Ao Caos'),
 (1, 'Damage Case'),
 (1, 'Damage Inc.'),
 (1, 'Dance'),
 (1, 'Dance Enquanto é Tempo'),
 (1, 'Dance Of Death'),
 (1, 'Dancing Barefoot'),
 (1, 'Dancing In The Street'),
 (1, 'Dandelion'),
 (1, 'Danny Boy, Danny Boy'),
 (1, 'Dança Da Solidão'),
 (1, 'Dark Corners'),
 (1, 'Dave'),
 (1, 'De Do Do Do, De Da Da Da'),
 (1, 'De Ja Vu'),
 (1, 'De La Luz'),
 (1, 'De Noite Na Cama'),
 (1, 'De Ouro E Marfim (Live)'),
 (1, 'Dead And Bloated'),
 (1, 'Dead Horse'),
 (1, 'Dee'),
 (1, 'Deep Waters'),
 (1, 'Deeper Underground'),
 (1, 'Deixa'),
 (1, 'Demorou!'),
 (1, 'Denúncia'),
 (1, 'Departure'),
 (1, 'Desaforo'),
 (1, 'Destitute Illusions'),
 (1, 'Deuce'),
 (1, 'Deus Ex Machina'),
 (1, 'Diamonds And Rust (Live)'),
 (1, 'Die Die My Darling'),
 (1, 'Die Walküre: The Ride of the Valkyries'),
 (1, 'Die With Your Boots On'),
 (1, 'Diga Lá, Coração'),
 (1, 'Din Din Wo (Little Child)'),
 (1, 'Dirty Little Thing'),
 (1, 'Dirty Love'),
 (1, 'Dirty Water Dog'),
 (1, 'Disappearing Act'),
 (1, 'Disarm'),
 (1, 'Discotheque'),
 (1, 'Disenchanted Lullaby'),
 (1, 'Disposable Heroes'),
 (1, 'Dissident'),
 (1, 'Distractions'),
 (1, 'Diversity Day'),
 (1, 'Divirta-Se (Saindo Da Sua)'),
 (1, 'Diwali'),
 (1, 'Do It For The Kids'),
 (1, 'Do You Feel Loved'),
 (1, 'Do You Have Other Loves?'),
 (1, 'Do You Like The Way'),
 (1, 'Do You Love Me'),
 (1, 'Do what cha wanna'),
 (1, "Doesn't Remind Me"),
 (1, 'Dog Eat Dog'),
 (1, 'Domingo'),
 (1, "Don't Cry"),
 (1, "Don't Cry (Original)"),
 (1, "Don't Damn Me"),
 (1, "Don't Go Back To Rockville"),
 (1, "Don't Look Back"),
 (1, "Don't Stand so Close to Me"),
 (1, "Don't You Cry"),
 (1, "Double Talkin' Jive"),
 (1, 'Doutor'),
 (1, 'Down By The Seaside'),
 (1, 'Down On The Corner'),
 (1, 'Down Under'),
 (1, 'Dreams'),
 (1, 'Drown'),
 (1, 'Drown Me Slowly'),
 (1, 'Drowning Man'),
 (1, 'Duelists'),
 (1, 'Duende'),
 (1, 'Dujji'),
 (1, "Dust N' Bones"),
 (1, 'E.C.T.'),
 (1, 'E.S.P.'),
 (1, 'Eclipse Oculto'),
 (1, 'Edie (Ciao Baby)'),
 (1, 'El Farol'),
 (1, 'Ela Disse Adeus'),
 (1, 'Elderly Woman Behind The Counter In A Small Town'),
 (1, 'Eleanor Rigby'),
 (1, 'Electrolite'),
 (1, 'Elza'),
 (1, 'Email Surveillance'),
 (1, 'Encontrar Alguém'),
 (1, 'Endgame'),
 (1, 'Enquanto O Dia Não Vem'),
 (1, 'Enter 77'),
 (1, 'Entrando Na Sua (Intro)'),
 (1, 'Entre E Ouça'),
 (1, 'Epic'),
 (1, 'Equinocio'),
 (1, 'Era Uma Vez'),
 (1, 'Esperando Na Janela'),
 (1, 'Esse Cara'),
 (1, 'Estranged'),
 (1, 'Estrela (Live)'),
 (1, 'Etnia'),
 (1, 'Eu Amo Você'),
 (1, 'Eu Apenas Queria Que Voçê Soubesse'),
 (1, 'Eu E Ela'),
 (1, 'Eu Sou Neguinha (Ao Vivo)'),
 (1, 'Eu Também Quero Beijar'),
 (1, 'Eu Vim Da Bahia - Live'),
 (1, 'Even Better Than The Real Thing'),
 (1, 'Everlong'),
 (1, 'Every Breath You Take'),
 (1, 'Every Time I Look At You'),
 (1, 'Everything I Need'),
 (1, "Everything's Ruined"),
 (1, 'Evil Dick'),
 (1, 'Evil Walks'),
 (1, 'Evil Ways'),
 (1, 'Evil Woman'),
 (1, 'Exodus (Part 2) [Season Finale]'),
 (1, 'Exodus, Pt. 1'),
 (1, 'Exodus, Pt. 2'),
 (1, 'Experiment In Terra'),
 (1, 'Exploder'),
 (1, 'Exposé'),
 (1, 'Expresso 2222'),
 (1, 'Extra'),
 (1, 'Extraordinary Girl'),
 (1, 'Eye'),
 (1, 'Eye Of The Beholder'),
 (1, 'F**k Me Pumps'),
 (1, "F*Ckin' Up"),
 (1, 'Face In The Sand'),
 (1, 'Faceless'),
 (1, 'Fade To Black'),
 (1, 'Fairies Wear Boots'),
 (1, 'Faixa Amarela'),
 (1, 'Falando De Amor'),
 (1, 'Falar A Verdade'),
 (1, 'Fall To Pieces'),
 (1, 'Falling To Pieces'),
 (1, 'Família'),
 (1, 'Fantasia On Greensleeves'),
 (1, 'Fascinação'),
 (1, 'Fast And Loose'),
 (1, 'Fast As a Shark'),
 (1, 'Fat Bottomed Girls'),
 (1, 'Fates Warning'),
 (1, 'Fear Is The Key'),
 (1, 'Feel It'),
 (1, 'Feel Your Love Tonight'),
 (1, 'Feirinha da Pavuna/Luz do Repente/Bagaço da Laranja'),
 (1, 'Felicidade Urgente'),
 (1, 'Fica'),
 (1, 'Fight From The Inside'),
 (1, 'Filho Maravilha'),
 (1, 'Finding My Way'),
 (1, 'Fire'),
 (1, 'Fire + Water'),
 (1, 'First Time I Met The Blues'),
 (1, 'Flash'),
 (1, 'Flash of The Blade'),
 (1, 'Flight Of The Rat'),
 (1, 'Flor De Lis'),
 (1, 'Flores'),
 (1, 'Flower'),

In [29]:
import sqlite3 
conn = sqlite3.connect('test.db')
cur = conn.cursor()

In [30]:
cur.execute("""CREATE TABLE cats (
                                    id INTEGER PRIMARY KEY,
                                    name TEXT,
                                    age INTEGER,
                                    breed TEXT
                                 )
            """
           )

In [42]:
# insert Maru into the pet_database.db here
cur.execute('''INSERT INTO cats (name, age, breed) 
                  VALUES ('fucktard', 3, 'mutt');
            '''
           )

In [35]:
cur.execute('''UPDATE cats SET name = "Hana" WHERE name = "Maru";''')

In [43]:
cur.execute('''select * from cats''').fetchall()

[(1, 'Hana', 3, 'Scottish Fold'), (2, 'fucktard', 3, 'mutt')]

In [39]:
cur.execute('''DELETE FROM cats WHERE id = 2;''')

In [44]:
# Commit your changes to the databaase
conn.commit()

In [46]:
#Preview the table via a second current cursor/connection 
#Don't overwrite the previous connection: you'll lose all of your work!
conn2 = sqlite3.connect('test.db')
cur2 = conn2.cursor()
cur2.execute("""select * from cats;""").fetchall()

[(1, 'Hana', 3, 'Scottish Fold'), (2, 'fucktard', 3, 'mutt')]

## Reflection