In [2]:
import pandas as pd
df = pd.read_csv("bom.movie_gross.csv.gz")

In [20]:
#some_dataframe.set_index("name_of_index_column", inplace=True)
#df.set_index('title', inplace=True)

KeyError: 'title'

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3387 entries, Toy Story 3 to An Actor Prepares
Data columns (total 4 columns):
studio            3382 non-null object
domestic_gross    3359 non-null float64
foreign_gross     2037 non-null object
year              3387 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.3+ KB

In [38]:
df.sort_values(by= 'domestic_gross')

,studio,domestic_gross,foreign_gross,year
title,,,,
Storage 24,Magn.,100.0,NaN,2013
The Chambermaid,FM,300.0,NaN,2015
News From Planet Mars,KL,300.0,NaN,2016
Satanic,Magn.,300.0,NaN,2016
Apartment 143,Magn.,400.0,426000,2012
2:22,Magn.,400.0,NaN,2017
Max & Leon,Distrib.,500.0,NaN,2017
Death of a Superhero,Trib.,600.0,NaN,2012
Amityville: The Awakening,W/Dim.,700.0,7700000,2017
Into the White,Magn.,700.0,NaN,2013
Down By Love,Distrib.,700.0,NaN,2016
It's All So Quiet (Boven is het stil),BWP,700.0,NaN,2015
Tough Being Loved By Jerks,KL,700.0,NaN,2015
Illegal (2011),FM,700.0,289000,2011
Jackpot,DR,800.0,1100000,2014
Perrier's Bounty,IFC,800.0,167000,2010
I Spit on Your Grave 2,Anch.,800.0,NaN,2013
REC 4: Apocalypse,Magn.,800.0,NaN,2015
Next Time I'll Aim for the Heart,Distrib.,800.0,NaN,2016
The Student and Mr. Henri,Distrib.,800.0,NaN,2016
The Decoy Bride,IFC,800.0,NaN,2012
Billy and Buddy,Distrib.,900.0,15200000,2013
Thanks to My Friends,Distrib.,900.0,NaN,2015
Khumba,MNE,1000.0,27200000,2013
Caught in the Web,Vita.,1100.0,NaN,2013
Skin Trade,Magn.,1200.0,NaN,2015
Billionaire Boy's Club,VE,1300.0,2500000,2018
An Invisible Sign,IFC,1300.0,NaN,2011
I Still See You,LGF,1400.0,1500000,2018
Little Girl (La Pivellina),FRun,1400.0,236000,2011
...,...,...,...,...
Black Panther,BV,700100000.0,646900000,2018
Star Wars: The Force Awakens,BV,936700000.0,"1,131.6",2015
It's a Wonderful Afterlife,UTV,NaN,1300000,2010
Celine: Through the Eyes of the World,Sony,NaN,119000,2010
White Lion,Scre.,NaN,99600,2010
Badmaash Company,Yash,NaN,64400,2010
Aashayein (Wishes),Relbig.,NaN,3800,2010
Force,FoxS,NaN,4800000,2011
Empire of Silver,NeoC,NaN,19000,2011
Solomon Kane,RTWC,NaN,19600000,2012
The Tall Man,Imag.,NaN,5200000,2012
Keith Lemon: The Film,NaN,NaN,4000000,2012
"Lula, Son of Brazil",NYer,NaN,3800000,2012
The Cup (2012),Myr.,NaN,1800000,2012
Dark Tide,WHE,NaN,432000,2012
The Green Wave,RF,NaN,70100,2012
22 Bullets,Cdgm.,NaN,21300000,2013
Matru Ki Bijlee Ka Mandola,FIP,NaN,6000000,2013
The Snitch Cartel,PI,NaN,2100000,2013
All the Boys Love Mandy Lane,RTWC,NaN,1900000,2013
6 Souls,RTWC,NaN,852000,2013
Jessabelle,LGF,NaN,7000000,2014
14 Blades,RTWC,NaN,3800000,2014
Jack and the Cuckoo-Clock Heart,Shout!,NaN,3400000,2014
Lila Lila,Crnth,NaN,1100000,2014
Surprise - Journey To The West,AR,NaN,49600000,2015
Finding Mr. Right 2,CL,NaN,114700000,2016
Solace,LGP,NaN,22400000,2016
Viral,W/Dim.,NaN,552000,2016
Secret Superstar,NaN,NaN,122000000,2017

In [4]:
df1 = pd.read_csv('imdb.name.basics.csv.gz')

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606648 entries, 0 to 606647
Data columns (total 6 columns):
nconst                606648 non-null object
primary_name          606648 non-null object
birth_year            82736 non-null float64
death_year            6783 non-null float64
primary_profession    555308 non-null object
known_for_titles      576444 non-null object
dtypes: float64(2), object(4)
memory usage: 27.8+ MB

In [31]:
df1

,nconst,primary_name,birth_year,death_year,primary_profession,known_for_titles
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer","tt0837562,tt2398241,tt0844471,tt0118553"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department","tt0896534,tt6791238,tt0287072,tt1682940"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer","tt1470654,tt0363631,tt0104030,tt0102898"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department","tt0114371,tt2004304,tt1618448,tt1224387"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator","tt0452644,tt0452692,tt3458030,tt2178256"
5,nm0062879,Ruel S. Bayani,NaN,NaN,"director,production_manager,miscellaneous","tt2590280,tt0352080,tt0216559,tt2057445"
6,nm0063198,Bayou,NaN,NaN,actor,"tt6579724,tt0093116"
7,nm0063432,Stevie Be-Zet,NaN,NaN,"composer,soundtrack","tt3106212,tt0478239,tt0264917,tt1626606"
8,nm0063618,Jeff Beal,1963.0,NaN,"composer,music_department,soundtrack","tt0183659,tt2545118,tt0384766,tt1856010"
9,nm0063750,Lindsay Beamish,NaN,NaN,"actress,miscellaneous","tt0404826,tt0111756,tt0367027,tt1492842"
10,nm0064023,Bryan Beasley,NaN,NaN,"director,producer,writer","tt3501180,tt1485100,tt1358897,tt1387162"
11,nm0064350,Martine Beauchemin,NaN,NaN,"producer,production_manager","tt5479010,tt0316463,tt1286159,tt0380732"
12,nm0065847,Michael Frost Beckner,1963.0,NaN,"writer,producer,miscellaneous","tt0108171,tt0095953,tt0266987,tt0285332"
13,nm0065919,Will Becton,NaN,NaN,"miscellaneous,editor,editorial_department","tt0478090,tt1334221,tt2249135,tt1522196"
14,nm0066093,Ahmad Bedair,1945.0,NaN,"actor,miscellaneous","tt2290391,tt0424830,tt0297398,tt2338117"
15,nm0066163,Arnaud Bedouët,NaN,NaN,"actor,writer,director","tt1355327,tt1977735,tt0173525,tt1710520"
16,nm0066268,Steve Mitchell Beebe,NaN,NaN,"editorial_department,director,editor","tt0827928,tt0119961,tt0408417,tt5521860"
17,nm0066897,Mohammad-Ali Behboudi,1956.0,NaN,actor,"tt6836462,tt4591834,tt0375911,tt2101473"
18,nm0067234,Hans Beimler,NaN,NaN,"producer,writer,miscellaneous","tt0486657,tt0092455,tt0091129,tt0106145"
19,nm0067845,Sondos Belhassen,NaN,NaN,actress,"tt0114103,tt0116209,tt1337140,tt0103806"
20,nm0067983,Krunoslav Belko,1971.0,NaN,actor,"tt1930421,tt0289360,tt0210629,tt3839316"
21,nm0068170,Dylan Bell,NaN,NaN,"director,actor,producer","tt4655766,tt3180116,tt8170168,tt4082762"
22,nm0068657,Philippe Bellaiche,NaN,NaN,"cinematographer,camera_department,producer","tt0309390,tt0285963,tt2091307,tt0498846"
23,nm0068874,Hava Kohav Beller,NaN,NaN,"director,writer,producer","tt0102778,tt7701650,tt0350668"
24,nm0069131,Gregg Bello,NaN,NaN,"actor,producer","tt1959490,tt5109784,tt1125849,tt0155267"
25,nm0069225,Gavin Bellour,NaN,NaN,"actor,producer,composer","tt0423370,tt2040257,tt0859592,tt7686128"
26,nm0069605,Bruno Beltramini,NaN,NaN,"cinematographer,visual_effects,camera_department","tt2154648,tt3746684,tt3746660,tt0427317"
27,nm0069757,Olga Belyavskaya,NaN,NaN,"actress,miscellaneous","tt0201345,tt7262530,tt0318034,tt1502417"
28,nm0069990,Jorge Ben Jor,1942.0,NaN,"soundtrack,composer,actor","tt0099892,tt3731562,tt1103275,tt0118655"
29,nm0070216,John Paul Fedele,NaN,NaN,"actor,cinematographer,special_effects","tt1424381,tt1075417,tt0453467,tt0268695"
...,...,...,...,...,...,...
606618,nm9969939,Anna Bligh,NaN,NaN,NaN,tt8694294
606619,nm9971271,Ray Spivey,NaN,NaN,"producer,writer,director",tt8697454
606620,nm9971456,Zheng Wei,NaN,NaN,director,NaN
606621,nm9975287,Oliver Delaby,NaN,NaN,actor,NaN
606622,nm9976388,Naomie Monplaisir,NaN,NaN,NaN,tt7948406
606623,nm9976769,Edyta Przytulska,NaN,NaN,actress,NaN
606624,nm9977609,Amenkai Pilgrim-Owens,NaN,NaN,writer,tt8709892
606625,nm9978371,Zach Campbell,NaN,NaN,"actor,cinematographer,assistant_director",NaN
606626,nm9979898,Ryosuke Yusa,NaN,NaN,actor,NaN
606627,nm9980588,Elina Gakou Gomba,NaN,NaN,writer,tt8081326
606628,nm9980896,Rama Narayanan,NaN,NaN,"director,writer","tt10127906,tt8715016,tt8919136,tt8929818"
606629,nm9981679,Samir Eshra,NaN,NaN,"director,writer,cinematographer",NaN
606630,nm9981999,Kamlesh Israni,NaN,NaN,actress,NaN
606631,nm9983730,Choi Yeong-Hwan,NaN,NaN,cinematographer,NaN
606632,nm9983906,Alejandro Odom,NaN,NaN,actor,tt8722030
606633,nm9985838,Anthony Simonetti,NaN,NaN,actor,tt8028908
606634,nm9985863,Gary Evans,NaN,NaN,producer,"tt0306913,tt8726188"
606635,nm9986856,Geraldine Caster,NaN,NaN,producer,tt8728296
606636,nm9988988,Sarla Verma,NaN,NaN,producer,tt8706386
606637,nm9989005,Jae-Hwan Kim,NaN,NaN,actor,NaN
606638,nm9989145,Szilvia Herr,NaN,NaN,actress,NaN
606639,nm9989840,Mariya Shekaturova,NaN,NaN,actor,tt5953804
606640,nm9989854,Layla Louise,1990.0,NaN,"actress,stunts","tt9910102,tt9898328,tt9335490,tt8894778"
606641,nm9990047,Joseph Jackson,NaN,NaN,actor,NaN
606642,nm9990296,Fleurette Dicaire,NaN,NaN,NaN,tt8319420
606643,nm9990381,Susan Grobes,NaN,NaN,actress,NaN
606644,nm9990690,Joo Yeon So,NaN,NaN,actress,"tt9090932,tt8737130"
606645,nm9991320,Madeline Smith,NaN,NaN,actress,"tt8734436,tt9615610"
606646,nm9991786,Michelle Modigliani,NaN,NaN,producer,NaN
606647,nm9993380,Pegasus Envoyé,NaN,NaN,"director,actor,writer",tt8743182

In [8]:
df2 = pd.read_csv('imdb.title.akas.csv.gz')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331703 entries, 0 to 331702
Data columns (total 8 columns):
title_id             331703 non-null object
ordering             331703 non-null int64
title                331703 non-null object
region               278410 non-null object
language             41715 non-null object
types                168447 non-null object
attributes           14925 non-null object
is_original_title    331678 non-null float64
dtypes: float64(1), int64(1), object(6)
memory usage: 20.2+ MB

In [23]:
df2.title_id.value_counts()

tt2488496    61
tt2310332    55
tt1201607    55
tt2948356    53
tt1790809    53
tt2278871    53
tt2452042    52
tt4630562    52
tt0892791    51
tt2820852    51
tt1217209    51
tt0398286    51
tt1345836    51
tt1596343    50
tt2527336    49
tt0848228    49
tt5323662    49
tt2096673    49
tt1905041    49
tt1399103    49
tt1568921    48
tt1318514    48
tt1637688    48
tt1104001    48
tt2294629    48
tt0369610    48
tt3691740    47
tt1170358    47
tt1453405    47
tt1408101    46
             ..
tt5300318     1
tt5103006     1
tt1667317     1
tt2990322     1
tt1670917     1
tt6583646     1
tt3833738     1
tt2622956     1
tt1594964     1
tt6269470     1
tt2255434     1
tt6125916     1
tt5132364     1
tt2311118     1
tt1620557     1
tt5914668     1
tt4998492     1
tt7024472     1
tt3509878     1
tt3717510     1
tt7056934     1
tt5742340     1
tt2331095     1
tt6166652     1
tt2753084     1
tt4956274     1
tt1725826     1
tt1671583     1
tt2438662     1
tt6661904     1
Name: title_id, Length: 122302, dtype: int64

In [ ]:
df1.df2

In [25]:
df3 = pd.read_csv('imdb.title.basics.csv.gz')
df3.head()

,tconst,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"

In [26]:
df3.set_index('primary_title', inplace=True)

In [27]:
df3

,tconst,original_title,start_year,runtime_minutes,genres
primary_title,,,,,
Sunghursh,tt0063540,Sunghursh,2013,175.0,"Action,Crime,Drama"
One Day Before the Rainy Season,tt0066787,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
The Other Side of the Wind,tt0069049,The Other Side of the Wind,2018,122.0,Drama
Sabse Bada Sukh,tt0069204,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
The Wandering Soap Opera,tt0100275,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
A Thin Life,tt0111414,A Thin Life,2018,75.0,Comedy
Bigfoot,tt0112502,Bigfoot,2017,NaN,"Horror,Thriller"
Joe Finds Grace,tt0137204,Joe Finds Grace,2017,83.0,"Adventure,Animation,Comedy"
O Silêncio,tt0139613,O Silêncio,2012,NaN,"Documentary,History"
Nema aviona za Zagreb,tt0144449,Nema aviona za Zagreb,2012,82.0,Biography
Pál Adrienn,tt0146592,Pál Adrienn,2010,136.0,Drama
So Much for Justice!,tt0154039,Oda az igazság,2010,100.0,History
Cooper and Hemingway: The True Gen,tt0159369,Cooper and Hemingway: The True Gen,2013,180.0,Documentary
Children of the Green Dragon,tt0162942,A zöld sárkány gyermekei,2010,89.0,Drama
T.G.M. - osvoboditel,tt0170651,T.G.M. - osvoboditel,2018,60.0,Documentary
The Tragedy of Man,tt0176694,Az ember tragédiája,2011,160.0,"Animation,Drama,History"
How Huang Fei-hong Rescued the Orphan from the Tiger's Den,tt0187902,How Huang Fei-hong Rescued the Orphan from the...,2011,NaN,NaN
Heaven & Hell,tt0192528,Reverse Heaven,2018,104.0,Drama
The Final Journey,tt0230212,The Final Journey,2010,120.0,Drama
Los pájaros se van con la muerte,tt0247643,Los pájaros se van con la muerte,2011,110.0,"Drama,Mystery"
Foodfight!,tt0249516,Foodfight!,2012,91.0,"Action,Animation,Comedy"
Godfather,tt0250404,Godfather,2012,NaN,"Crime,Drama"
Gangavataran,tt0253093,Gangavataran,2018,134.0,NaN
Return to Babylon,tt0255820,Return to Babylon,2013,75.0,"Biography,Comedy,Drama"
Akakis mogzauroba,tt0262218,Akakis mogzauroba,2012,44.0,Documentary
Seven Jews from My Class,tt0262759,Siedmiu Zydów z mojej klasy,2018,40.0,Documentary
On kadin,tt0263814,On kadin,2019,NaN,Drama
To Chase a Million,tt0276568,To Chase a Million,2018,97.0,"Action,Drama"
Prague: The Restless Heart of Europe,tt0277964,Praha - neklidné srdce Evropy,2018,59.0,"Documentary,History"
Short Time Heroes,tt0283440,Kurzzeithelden,2015,45.0,Sci-Fi
...,...,...,...,...,...
Swarm Season,tt9913056,Swarm Season,2019,86.0,Documentary
Diabolik sono io,tt9913084,Diabolik sono io,2019,75.0,Documentary
Nepal - Homebird,tt9913248,Nepal - Homebird,2019,52.0,Documentary
Fragments,tt9913418,Fragments,2019,NaN,"Drama,Mystery,Sci-Fi"
Marley G Documentary,tt9913572,Marley G Documentary,2019,NaN,Documentary
Bacchanalia,tt9913594,Bacchanalia,2017,72.0,"Drama,Mystery,Thriller"
Paradise,tt9913936,Paradise,2019,NaN,"Crime,Drama"
A Cherry Tale,tt9914254,Kirsebæreventyret,2019,85.0,Documentary
Sokagin Çocuklari,tt9914286,Sokagin Çocuklari,2019,98.0,"Drama,Family"
Kuttram Seiyel,tt9914368,Kuttram Seiyel,2019,NaN,"Action,Crime"
The Holden Family Plan,tt9914522,The Holden Family Plan,2019,NaN,"Drama,Family"
Albatross,tt9914642,Albatross,2017,NaN,Documentary
9/11: Escape from the Towers,tt9914644,9/11: Escape from the Towers,2018,120.0,Documentary
Wien is 't Hof van Commerce,tt9914662,Wien is 't Hof van Commerce,2018,NaN,Comedy
The War of Godzilla,tt9914828,The War of Godzilla,2015,102.0,"Action,Comedy,Family"
La vida sense la Sara Amat,tt9914942,La vida sense la Sara Amat,2019,NaN,NaN
Vida em Movimento,tt9915436,Vida em Movimento,2019,70.0,Documentary
Bobbyr Bondhura,tt9915790,Bobbyr Bondhura,2019,NaN,Family
The Last White Witch,tt9915872,The Last White Witch,2019,97.0,"Comedy,Drama,Fantasy"
The Mystery of a Buryat Lama,tt9916132,The Mystery of a Buryat Lama,2018,94.0,"Biography,Documentary,History"
Drømmeland,tt9916160,Drømmeland,2019,72.0,Documentary
The Rehearsal,tt9916170,O Ensaio,2019,51.0,Drama
Illenau - die Geschichte einer ehemaligen Heil- und Pflegeanstalt,tt9916186,Illenau - die Geschichte einer ehemaligen Heil...,2017,84.0,Documentary
Safeguard,tt9916190,Safeguard,2019,90.0,"Drama,Thriller"
The Secret of China,tt9916428,The Secret of China,2019,NaN,"Adventure,History,War"
Kuambil Lagi Hatiku,tt9916538,Kuambil Lagi Hatiku,2019,123.0,Drama
Rodolpho Teóphilo - O Legado de um Pioneiro,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
Dankyavar Danka,tt9916706,Dankyavar Danka,2013,NaN,Comedy
6 Gunn,tt9916730,6 Gunn,2017,116.0,NaN
Chico Albuquerque - Revelações,tt9916754,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [28]:
#joined_df = df1.join(df2, how='inner')
joined = df.join(df3, how='inner')
joined.head()

,studio,domestic_gross,foreign_gross,year,tconst,original_title,start_year,runtime_minutes,genres
'71,RAtt.,1300000.0,355000,2015,tt2614684,'71,2014,99.0,"Action,Drama,Thriller"
"1,000 Times Good Night",FM,53900.0,NaN,2014,tt2353767,Tusen ganger god natt,2013,117.0,"Drama,War"
10 Cloverfield Lane,Par.,72100000.0,38100000,2016,tt1179933,10 Cloverfield Lane,2016,103.0,"Drama,Horror,Mystery"
10 Years,Anch.,203000.0,NaN,2012,tt1715873,10 Years,2011,100.0,"Comedy,Drama,Romance"
1001 Grams,KL,11000.0,NaN,2015,tt3346824,1001 Gram,2014,93.0,Drama

In [29]:
joined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3366 entries, '71 to Zootopia
Data columns (total 9 columns):
studio             3363 non-null object
domestic_gross     3342 non-null float64
foreign_gross      2043 non-null object
year               3366 non-null int64
tconst             3366 non-null object
original_title     3366 non-null object
start_year         3366 non-null int64
runtime_minutes    3198 non-null float64
genres             3326 non-null object
dtypes: float64(2), int64(2), object(5)
memory usage: 263.0+ KB

In [14]:
df4 = pd.read_csv('imdb.title.crew.csv.gz')
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146144 entries, 0 to 146143
Data columns (total 3 columns):
tconst       146144 non-null object
directors    140417 non-null object
writers      110261 non-null object
dtypes: object(3)
memory usage: 3.3+ MB

In [15]:
df4.head()

      tconst                      directors              writers
0  tt0285252                      nm0899854            nm0899854
1  tt0438973                            NaN  nm0175726,nm1802864
2  tt0462036                      nm1940585            nm1940585
3  tt0835418                      nm0151540  nm0310087,nm0841532
4  tt0878654  nm0089502,nm2291498,nm2292011            nm0284943

In [16]:
df5 = pd.read_csv('imdb.title.principals.csv.gz')
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028186 entries, 0 to 1028185
Data columns (total 6 columns):
tconst        1028186 non-null object
ordering      1028186 non-null int64
nconst        1028186 non-null object
category      1028186 non-null object
job           177684 non-null object
characters    393360 non-null object
dtypes: int64(1), object(5)
memory usage: 47.1+ MB

In [17]:
df5.head()

      tconst  ordering     nconst  category       job        characters
0  tt0111414         1  nm0246005     actor       NaN       ["The Man"]
1  tt0111414         2  nm0398271  director       NaN               NaN
2  tt0111414         3  nm3739909  producer  producer               NaN
3  tt0323808        10  nm0059247    editor       NaN               NaN
4  tt0323808         1  nm3579312   actress       NaN  ["Beth Boothby"]

In [32]:
df6 = pd.read_csv('imdb.title.ratings.csv.gz')
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73856 entries, 0 to 73855
Data columns (total 3 columns):
tconst           73856 non-null object
averagerating    73856 non-null float64
numvotes         73856 non-null int64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.7+ MB

In [33]:
df6.head()

       tconst  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21